---
title: "Describe public dataset"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms/')
```

# Environment

```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse","countrycode") 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()
```

# Load data
```{r}
public_dataset <- readRDS("./data/public_genomes/NCBI_metadata/NCBI_Pathogens_Kpn_metadata_isolates_w_spatiotemporal_data_121025.RDS")
public_dataset$assembly_name <- public_dataset$Assembly
paste0("Public genomes with isolate and spatiotemporal data: ",nrow(public_dataset))
kleborate_genome_list <- readLines("./data/public_genomes/kleborate/partitions/NCBI_pathogens_genome_assembly_list.txt")
kleborate_genome_name <- str_split(kleborate_genome_list,pattern = '/',simplify = T) %>% .[,15]
paste0("Public genomes tested for Kleborate: ",length(kleborate_genome_list))
kleborate <- read_delim("./data/public_genomes/kleborate/results/NCBI_pathogens_Kpn_kleborate.txt")
kleborate$assembly_name <- str_split(kleborate$strain,pattern = '_',simplify = T)   %>% .[,c(1,2)] %>% apply(.,1,paste0,collapse='_')
paste0("Public genomes with Kleborate Kpn species complex entry: ",nrow(kleborate))
paste0("Public genomes withiout Kleborate Kpn species complex entry: ",length(kleborate_genome_list) - nrow(kleborate))
public_dataset <- left_join(public_dataset,kleborate)
```

# Subset dataset to confident strains
```{r}
table(public_dataset$species,public_dataset$species_match)
table(public_dataset$species,public_dataset$QC_warnings)

public_dataset_kleborate_cleaned <- public_dataset %>% subset(species== "Klebsiella pneumoniae" & species_match == 'strong' & QC_warnings == '-')
```

# ST data
```{r}
ST_over_01_percent <- table(public_dataset_kleborate_cleaned$ST)  %>% subset(.> c(nrow(public_dataset_kleborate_cleaned)*0.001)) %>% names
ST_over_05_percent <- table(public_dataset_kleborate_cleaned$ST)  %>% subset(.> c(nrow(public_dataset_kleborate_cleaned)*0.005)) %>% names
public_dataset_kleborate_cleaned$ST_recode <- ifelse(public_dataset_kleborate_cleaned$ST %in% ST_over_01_percent,public_dataset_kleborate_cleaned$ST,"Other ST")
public_dataset_kleborate_cleaned$major_global_STs <- ifelse(public_dataset_kleborate_cleaned$ST %in% ST_over_05_percent,public_dataset_kleborate_cleaned$ST,"ST < 0.5%")
public_dataset_kleborate_cleaned$ST258 <- public_dataset_kleborate_cleaned$ST == "ST258"
public_dataset_kleborate_cleaned$ST14 <- public_dataset_kleborate_cleaned$ST == "ST14"
public_dataset_kleborate_cleaned$ST307 <- public_dataset_kleborate_cleaned$ST == "ST307"
public_dataset_kleborate_cleaned$ST17 <- public_dataset_kleborate_cleaned$ST == "ST17"
public_dataset_kleborate_cleaned$ST_of_interest <- ifelse(public_dataset_kleborate_cleaned$ST %in% c("ST258","ST14","ST307","ST17"),public_dataset_kleborate_cleaned$ST,"Other ST")
table(public_dataset_kleborate_cleaned$ST_recode) %>% sort

ggplot(data=public_dataset_kleborate_cleaned,aes(x=forcats::fct_infreq(ST_recode))) + geom_bar(fill='black') + theme_bw() + theme(axis.text.x = element_text(angle=90,vjust=1,hjust=1)) 
ggplot(data=public_dataset_kleborate_cleaned,aes(x=forcats::fct_infreq(major_global_STs))) + geom_bar(fill='black') + theme_bw() + theme(axis.text.x = element_text(angle=90,vjust=1,hjust=1)) 
ggplot(data=public_dataset_kleborate_cleaned,aes(x=collection_year,fill=forcats::fct_infreq(major_global_STs))) + geom_bar() + theme_bw() 
ggplot(data=public_dataset_kleborate_cleaned %>% subset(collection_year>1995),aes(x=collection_year,fill=forcats::fct_infreq(major_global_STs))) + geom_bar() + theme_bw()  + hues::scale_fill_iwanthue()
ggplot(data=public_dataset_kleborate_cleaned %>% subset(collection_year>1995 & country == "United States"),aes(x=collection_year,fill=forcats::fct_infreq(major_global_STs))) + geom_bar() + theme_bw()  + hues::scale_fill_iwanthue()
ggplot(data=public_dataset_kleborate_cleaned %>% subset(collection_year>1995 & country=="United States"),aes(x=collection_year,fill=forcats::fct_infreq(major_global_STs))) + geom_bar() + theme_bw()  + hues::scale_fill_iwanthue()
ggplot(data=public_dataset_kleborate_cleaned %>% subset(collection_year>1995 & california == T),aes(x=collection_year,fill=forcats::fct_infreq(major_global_STs))) + geom_bar() + theme_bw()  + hues::scale_fill_iwanthue()
```

# Time
```{r}
unique_years <- length(unique(public_dataset_kleborate_cleaned$collection_year))
ggplot(data=public_dataset_kleborate_cleaned,aes(x=collection_year)) + geom_histogram(fill='black',bins = unique_years) + theme_bw()

get_decade <- function(date){
  date - (date %% 10) 
}
public_dataset_kleborate_cleaned$decade <- get_decade(public_dataset_kleborate_cleaned$collection_year)

ggplot(data=public_dataset_kleborate_cleaned,aes(x=as.factor(decade))) + geom_bar(stat='count',fill='black',bins = unique_years) + theme_bw()   
```

# Geography
```{r}
ggplot(data=public_dataset_kleborate_cleaned,aes(x=forcats::fct_infreq(continent))) + geom_bar(stat='count',fill='black',bins = unique_years) + theme_bw()

ggplot(data=public_dataset_kleborate_cleaned,aes(x=forcats::fct_infreq(country))) + geom_bar(stat='count',fill='black',bins = unique_years) + theme_bw() + theme(axis.text.x = element_text(angle = 90,vjust=0.5,hjust=1)) 
```

# United states
```{r}
public_dataset_kleborate_cleaned_US <- subset(public_dataset_kleborate_cleaned %>% subset(country == "United States"))

A <- ggplot(data=public_dataset_kleborate_cleaned_US,aes(x=california,fill=california)) + geom_bar() + theme_bw()

B <- ggplot(data=public_dataset_kleborate_cleaned_US,aes(x=collection_year)) + geom_histogram(bins = n_distinct(public_dataset_kleborate_cleaned_US$collection_year)) + theme_bw()

C <- ggplot(data=public_dataset_kleborate_cleaned_US,aes(x=forcats::fct_infreq(ST_recode))) + geom_bar() + theme_bw() + theme(axis.text.x = element_text(angle=90,hjust=1,vjust=1))

D <- ggplot(data=public_dataset_kleborate_cleaned_US %>% subset(collection_year>1995),aes(x=collection_date,fill=ST_of_interest)) + geom_histogram(bins = n_distinct(public_dataset_kleborate_cleaned_US$collection_year)) + theme_bw()  + hues::scale_fill_iwanthue() + facet_wrap(~ST_of_interest,scales = 'free_y') 
```


# California
```{r}
public_dataset_kleborate_cleaned_CA <- subset(public_dataset_kleborate_cleaned %>% subset(california ==T)) 

A <- ggplot(data=public_dataset_kleborate_cleaned_CA,aes(x=collection_year,fill=forcats::fct_infreq(major_global_STs))) + geom_bar() + theme_bw()  + hues::scale_fill_iwanthue()

B <- ggplot(data=public_dataset_kleborate_cleaned_CA %>% subset(collection_year>1995),aes(x=collection_date,fill=ST_of_interest)) + geom_histogram(bins = n_distinct(public_dataset_kleborate_cleaned_US$collection_year)) + theme_bw()  + hues::scale_fill_iwanthue() + facet_wrap(~ST_of_interest,scales = 'free_y') 
```

# ST258
```{r,fig.width=7.5,fig.height=15}

public_dataset_kleborate_cleaned$GD_insertion <- grepl("OmpK36GD",public_dataset_kleborate_cleaned$Omp_mutations)
public_dataset_kleborate_cleaned$Colistin_resistance <- public_dataset_kleborate_cleaned$resistance_score==3
public_dataset_kleborate_cleaned$kfoC_missing <- grepl("kfoC",public_dataset_kleborate_cleaned$O_Missing_expected_genes)
public_dataset_kleborate_cleaned$KL107 <- public_dataset_kleborate_cleaned$K_locus== "KL107"
public_dataset_kleborate_cleaned$KL106 <- public_dataset_kleborate_cleaned$K_locus== "KL106"
public_dataset_kleborate_cleaned$KPC <- grepl("KPC",public_dataset_kleborate_cleaned$Bla_Carb_acquired)
public_dataset_kleborate_cleaned$NDM <- grepl("NDM",public_dataset_kleborate_cleaned$Bla_Carb_acquired)
public_dataset_kleborate_cleaned$KPC3 <- grepl("KPC-3",public_dataset_kleborate_cleaned$Bla_Carb_acquired) &  grepl("KPC-35",public_dataset_kleborate_cleaned$Bla_Carb_acquired) ==F
public_dataset_kleborate_cleaned$KPC2 <- grepl("KPC-2",public_dataset_kleborate_cleaned$Bla_Carb_acquired) &  grepl("KPC-23",public_dataset_kleborate_cleaned$Bla_Carb_acquired) ==F
public_dataset_kleborate_cleaned$KPC2_GD_insertion <- public_dataset_kleborate_cleaned$KPC2 & public_dataset_kleborate_cleaned$GD_insertion
public_dataset_kleborate_cleaned$KPC2_GD_insertion_KL106 <- public_dataset_kleborate_cleaned$KPC2 & public_dataset_kleborate_cleaned$GD_insertion & public_dataset_kleborate_cleaned$KL106


public_dataset_kleborate_cleaned_ST258 <- subset(public_dataset_kleborate_cleaned,ST=='ST258')
make_prop_plot <- function(df,variable){
  unique_years <- length(df$collection_year)
  dataset_by_year <- df %>% group_by(collection_year) %>% summarise(n=sum(get(variable)),total_in_year = length(collection_year), perc = n/total_in_year*100)
  ggplot(data=dataset_by_year,aes(x=collection_year,y =perc)) + geom_bar(stat='identity',fill='black',bins = unique_years) + theme_bw() + scale_fill_manual(breaks = c(T,F),labels = c("Present","Absent"),values = c("black","gray"))  + xlab("Year") + ylab(paste0("% ",variable,"+")) + ylim(NA,100.1)
}
 
A <- ggplot(data=public_dataset_kleborate_cleaned_ST258,aes(x=collection_year,fill=continent)) + geom_histogram(bins= n_distinct(public_dataset_kleborate_cleaned_ST258$collection_year)) + theme_bw()   + xlab("Year") + ylab("ST258 Count") + hues::scale_fill_iwanthue()
B <- ggplot(data=public_dataset_kleborate_cleaned_ST258,aes(x=collection_year,fill=forcats::fct_infreq(country))) + geom_histogram(bins= n_distinct(public_dataset_kleborate_cleaned_ST258$collection_year)) + theme_bw()   + xlab("Year") + ylab("ST258 Count") + hues::scale_fill_iwanthue()
C <- ggplot(data=public_dataset_kleborate_cleaned_ST258,aes(x=collection_year,fill=forcats::fct_infreq(K_locus))) + geom_histogram(bins= n_distinct(public_dataset_kleborate_cleaned_ST258$collection_year)) + theme_bw()   + xlab("Year") + ylab("ST258 Count") + hues::scale_fill_iwanthue()
D <- ggplot(data=public_dataset_kleborate_cleaned_ST258,aes(x=collection_year,fill=forcats::fct_infreq(O_locus))) + geom_histogram(bins= n_distinct(public_dataset_kleborate_cleaned_ST258$collection_year)) + theme_bw()   + xlab("Year") + ylab("ST258 Count") + hues::scale_fill_iwanthue()


B <- ggplot(data=public_dataset_kleborate_cleaned_ST258,aes(x=collection_year,fill=virulence_score)) + geom_histogram(bins= n_distinct(public_dataset_kleborate_cleaned_ST258$collection_year)) + theme_bw()   + xlab("Year") + ylab("ST258 Count") + hues::scale_fill_iwanthue()
 
A <- make_prop_plot(df = public_dataset_kleborate_cleaned_ST258, variable = 'Colistin_resistance')
B <- make_prop_plot(df = public_dataset_kleborate_cleaned_ST258, variable = 'KL107')
C <- make_prop_plot(df = public_dataset_kleborate_cleaned_ST258, variable = 'KL106')
D <- make_prop_plot(df = public_dataset_kleborate_cleaned_ST258, variable = 'kfoC_missing')
E <- make_prop_plot(df = public_dataset_kleborate_cleaned_ST258, variable = 'KPC3')
f <- make_prop_plot(df = public_dataset_kleborate_cleaned_ST258, variable = 'KPC2')
G <- make_prop_plot(df = public_dataset_kleborate_cleaned_ST258, variable = 'GD_insertion')
H <- make_prop_plot(df = public_dataset_kleborate_cleaned_ST258, variable = 'KPC2_GD_insertion')
I <- make_prop_plot(df = public_dataset_kleborate_cleaned_ST258, variable = 'KPC2_GD_insertion_KL106')

cowplot::plot_grid(A,B,C,D,E,f,G,H,I,ncol=1)
```

