---
title: "Figure 1: Sampling dynamics"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms')
```

# Environment
```{r}
# Packages
packages <- c("tidyverse","gridExtra","kableExtra","cowplot","forcats","ggalluvial")
lapply(packages,library,character.only=T)

# Functions
source("./lib/consistent_themes.R")

# Print environment
Sys.info()
sessionInfo() 
```

# Load data
```{r}
df <- readRDS("./data/dataset/CA_LTACH_first_clinical_per_quarter_CRKP_genomes_merged_studies_metadata.RDS")   

df_201415 <- df%>% subset(study == "2014-15")
df_202123 <- df%>% subset(study == "2021-23")

df_202123_all <- readRDS("./data/dataset/CA_LTACH_CRE_genomes_merged_studies_metadata.RDS") %>% subset(study == '2021-23')

number_of_weeks_1415 <- as.numeric(round(difftime(max(df_201415$date,na.rm = T),min(df_201415$date,na.rm = T),units = 'weeks')) + 1)
number_of_weeks_2123 <- as.numeric(round(difftime(max(df_202123_all$date,na.rm = T),min(df_202123_all$date,na.rm = T),units = 'weeks')) + 1)
```

## A. 2014-15
```{r}
A <- ggplot(data = df %>% subset(study == "2014-15")) +
  geom_histogram(
    aes(x = date, fill = study),  # << key addition
    bins = number_of_weeks_1415) +
  xlab("Collection date") +
  ylab("Isolates") +
  theme_bw_me +
  scale_x_date(
    date_breaks = "3 months",
    date_labels = "%m-%Y") +
  study_color_fill +
  theme(
    legend.position = 'none',
    axis.text = element_text(size=10, color="black"),
    axis.title = element_text(size=12, color="black"),
    legend.text = element_text(size=10, color="black"),
    legend.title = element_text(size=12, color="black"),
    plot.title = element_text(size=0, color="black")) + ylim(NA,15.1)
```

## B. 2021-23
```{r}      
B <- ggplot(data = df %>% subset(study == "2021-23")) +
  geom_histogram(
    aes(x = date, fill = study),  # << key addition
    bins = number_of_weeks_2123) +
  xlab("Collection date") +
  ylab("Isolates") +
  theme_bw_me +
  scale_x_date(
    date_breaks = "6 months",
    date_labels = "%m-%Y") +
  study_color_fill +
  theme(
    legend.position = 'none',
    axis.text = element_text(size=10, color="black",hjust=0.5,vjust=0.5),
    axis.title = element_text(size=12, color="black"),
    legend.text = element_text(size=10, color="black"),
    legend.title = element_text(size=12, color="black"),
    plot.title = element_text(size=0, color="black")) + ylim(NA,15.1)
```

# C & D. Source differences
```{r} 
df$source_simplified <- str_to_title(df$source_simplified)
df$source_simplified <- factor(df$source_simplified,levels = c(df %>% group_by(source_simplified) %>% summarise (n=n()) %>% arrange(-n) %>% .$source_simplified))

source_scale <- scale_fill_manual(breaks = levels(df$source_simplified),values = c(hues::iwanthue(n = length(unique(df$source_simplified)))),name = "Source", guide = guide_legend(ncol=1, title.position = "top", label.position = "right")) 

source_dist <-  df %>% subset(is.na(source_simplified)==F)   %>%
  count(study, source_simplified) %>%
  complete(study, source_simplified, fill = list(n = 0)) %>%
  group_by(study) %>%
  mutate(prop = n / sum(n) * 100)
   
source_dist$source_simplified <- factor(source_dist$source_simplified,levels = source_dist %>% subset(study =='2021-23') %>% arrange(n) %>% group_by(source_simplified) %>% summarise (n = sum(n)) %>% arrange(-n) %>% .$source_simplified) 

C <- ggplot(data=df,aes(y=source_simplified,fill=source_simplified)) + geom_bar() +
  geom_text(stat='count',
            aes(label=..count..),
            hjust=-0.05, 
            size=3.5) + 
  xlim(NA, 205.1) +
  theme_bw_me +
  xlab("Isolates") + ylab("") +
  theme(
    axis.text.x = element_text(hjust = 0.5, size=10, color="black"),
    axis.text.y = element_text(size=10, color="black"),
    axis.title = element_text(size = 12, color="black"),
                  legend.text =   element_text(size=10, color="black"),
                  legend.title = element_text(size = 10, color="black"),
    plot.title = element_text(size = 0, color="black"),
    legend.position = "none",
    strip.text = element_text(size=12,color='black')
  ) + source_scale + facet_wrap(~study)


D <- ggplot(source_dist %>% subset(n>0),aes(x = study,stratum = source_simplified,alluvium = source_simplified,y=prop,fill = source_simplified)) +
  geom_alluvium(aes(fill = source_simplified),width=0.66,alpha=0.75) +
  geom_stratum(width=0.66) + theme_bw_me + xlab("Study") + ylab("Percentage (%)") + source_scale + theme(legend.position = "right",
                  axis.text =   element_text(size=10, color="black"),
                  axis.title = element_text(size = 12, color="black"),
                  legend.text =   element_text(size=10, color="black"),
                  legend.title = element_text(size = 12, color="black"),
                  plot.title = element_text(size = 0, color="black")) + theme(legend.position='none')
```
 
# E. Sample counts by facility
```{r}
df_complete <- df %>%
  count(hospital_location_recode, study) %>%
  complete(hospital_location_recode, study)  

df_complete$prop <- ifelse(df_complete$study=='2021-23',df_complete$n / sum(df_complete %>% subset(study == '2021-23') %>% .$n,na.rm=T),df_complete$n / sum(df_complete %>% subset(study == '2014-15') %>% .$n,na.rm=T))
df_complete$perc <- df_complete$prop *100 

# Group df_complete by study and have proportion be n per hospital location
df_complete <- df_complete %>% group_by(study,hospital_location_recode)  

df_complete$hospital_location_recode <- factor(
  df_complete$hospital_location_recode,
  levels = df_complete %>% subset(study == "2021-23") %>% 
    group_by(hospital_location_recode) %>%
    summarise(n = sum(n, na.rm = TRUE)) %>%
    arrange(-n) %>%
    pull(hospital_location_recode)
)

df_complete$study <- factor(df_complete$study ,levels = c("2021-23","2014-15"))

E <- ggplot(data = df_complete) +
  geom_bar(
    aes(x = n, y = hospital_location_recode, fill = study),
    stat = "identity",
    position = position_dodge(width = 0.9)
  ) +
  geom_text(
    aes(x = n, y = hospital_location_recode, label = n, group = study),
    position = position_dodge(width = 0.9),
    hjust = -0.2,
    size = 2.5
  ) +
  xlab("Isolates") +
  ylab("") +
  xlim(NA, 72) +
  theme_bw_me +
  labs(fill = "Study") +
  study_color_fill +
  theme(legend.position='bottom',
    axis.text = element_text(size = 10, color = "black",hjust=0.5,vjust=0.5),
    axis.title = element_text(size = 12, color = "black"), 
    legend.text = element_text(size = 10, color = "black"),
    legend.title = element_text(size = 12, color = "black"),
    plot.title = element_text(size = 0, color = "black")
  )  
```

## F. Proportion by study
```{r}
f <- ggplot(data = df_complete) +
  geom_bar(
    aes(x = perc, y = hospital_location_recode, fill = study),
    stat = "identity",
    position = position_dodge(width = 0.9)
  ) +
  geom_text(
    aes(x = perc, y = hospital_location_recode, label = round(perc,2), group = study),
    position = position_dodge(width = 0.9),
    hjust = -0.2,
    size = 2.5
  ) +
  xlab("Percentage (%)") +
  ylab("") +
  xlim(NA, 20.01) +
  theme_bw_me +
  labs(fill = "Study") +
  study_color_fill +
  theme(legend.position='bottom',
    axis.text = element_text(size = 10, color = "black",hjust=0.5,vjust=0.5),
    axis.title = element_text(size = 12, color = "black"), 
    legend.text = element_text(size = 10, color = "black"),
    legend.title = element_text(size = 12, color = "black"),
    plot.title = element_text(size = 0, color = "black"))
```

```{r,fig.width=8,fig.height=8} 
AB <- cowplot::plot_grid(A,B + theme(legend.position = 'none'),ncol=2,labels =c("A","B"),rel_widths = c(1,1))
CD <- cowplot::plot_grid(C,D,ncol=2,labels = c("C","D"),rel_widths = c(1,0.5))
EF <-  cowplot::plot_grid(E+ theme(legend.position = 'none'),f + theme(legend.position = 'none'),ncol=2,labels =c("E","F"),rel_widths = c(1,1))

figure1 <- cowplot::plot_grid(AB,CD,EF,ncol=1,rel_heights = c(0.65,0.65,1))
figure1 
``` 

```{r}
ggsave(filename = "./figures/figure_1_sampling.png",plot=figure1,width = 8,height = 8,dpi=900,bg = 'white')
```
