---
title: "Figure 3: Carbapenemase plasmids"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms')
```

# Environment

```{r}
# Packages
packages <- c("tidyverse","gridExtra","kableExtra","tableone","cowplot","ComplexHeatmap",'ggalluvial')
lapply(packages,library,character.only=T)

# Functions
source("./lib/consistent_themes.R")

# Print environment
Sys.info()
sessionInfo()
```

# Load data

```{r}
df <- readRDS("./data/dataset/CA_LTACH_first_clinical_per_quarter_CRKP_genomes_merged_studies_metadata.RDS")   
```

# Coordinate sequence type data

```{r} 
df$Species_ST_recode_no_species <- gsub("Klebsiella pneumoniae ","",df$Species_ST)
 
df_201415 <- df%>% subset(study == "2014-15")
df_202123<- df%>% subset(study == "2021-23")
```

# Load carbapenemase data
```{r}
carbapenemase_content <- readRDS("./data/carbapenemase_content/carbapenemase_content_merged_studies.RDS")
df <- left_join(df,carbapenemase_content)
```

# Load plasmid data
```{r}
mobtyper_merged <- readRDS("./data/mobsuite/mobtyper_merged_w_carbapenemase_data.RDS") %>% subset(isolate_no %in% df$isolate_no)
```

# A. KPC plasmids
```{r} 
df_split <-  df %>%
  separate_rows(carbapenemase_plasmid, sep = " & ")

mobtyper_perc <-  df_split   %>%
  count(study, carbapenemase_plasmid) %>%
  complete(study, carbapenemase_plasmid, fill = list(n = 0)) %>%
  group_by(study) %>%
  mutate(perc = n / sum(n) * 100) 
 
df_split$carbapenemase_plasmid <- factor(df_split$carbapenemase_plasmid,levels = plasmid_fill_scale$breaks)

A <- ggplot(data=df_split ,aes(y=carbapenemase_plasmid,fill=carbapenemase_plasmid)) + geom_bar(stat='count')  + theme_bw_me + ylab("") + facet_wrap(~study) + plasmid_fill_scale  + xlab("Isolates") + theme(legend.position = 'none') +
  geom_text(stat='count',
            aes(label=..count..),
            hjust=-0.05, 
            size=3.5)  + xlim(NA,140.1) +
  theme(
    axis.text.x = element_text(hjust = 0.5, size=12, color="black"),
    axis.text.y = element_text(size=12, color="black"),
    axis.title = element_text(size = 14, color="black"),
                  legend.text =   element_text(size=12, color="black"),
                  legend.title = element_text(size = 12, color="black"),
    plot.title = element_text(size = 0, color="black"),
    legend.position = "none",
    strip.text = element_text(size=14,color='black' )
  )   + scale_x_continuous(breaks = scales::pretty_breaks(6),limits = c(0,max(mobtyper_perc$n)+8))
A
```

## C. Species ST
```{r}  
df$Species_ST_recode <- factor(df$Species_ST_recode,levels = ST_scale$breaks)

carbapenemase_plasmid_percentage_ST_data <- df  %>%
  count(study, Species_ST_recode,carbapenemase_plasmid) %>%
  complete(study, Species_ST_recode, fill = list(n = 0)) %>%
  group_by(study,Species_ST_recode) %>%
  mutate(perc = n / sum(n) * 100)  

carbapenemase_plasmid_percentage_ST_data <- carbapenemase_plasmid_percentage_ST_data %>%
  mutate(
    carb_parts = str_split(carbapenemase_plasmid, " & "),
    carb_plasmid_primary = map_chr(carb_parts, 1),
    carb_secondary_raw = map_chr(carb_parts, ~ if (length(.) > 1) .[2] else NA_character_),
    carb_plasmid_secondary = ifelse(is.na(carb_secondary_raw), NA_character_, carb_secondary_raw)
  ) %>%
  select(-carb_parts, -carb_secondary_raw)

carbapenemase_plasmid_percentage_ST_data$carb_plasmid_primary <-  factor(carbapenemase_plasmid_percentage_ST_data$carb_plasmid_primary,levels =plasmid_fill_scale$breaks)

carbapenemase_plasmid_percentage_ST_data$Species_ST_recode <- factor(carbapenemase_plasmid_percentage_ST_data$Species_ST_recode,levels = ST_scale$breaks)

carbapenemase_plasmid_percentage_ST_data <- subset(carbapenemase_plasmid_percentage_ST_data,perc>0)

C <- ggplot(
  data = carbapenemase_plasmid_percentage_ST_data,
  aes(
    y = Species_ST_recode,
    x = perc,
    fill = carb_plasmid_primary,
    colour = carb_plasmid_secondary
  )
) +
  geom_bar(stat = "identity",linewidth = 0.66)  +  plasmid_color_scale +
  theme_bw_me +
  xlab("Percentage of isolates") + ylab("") +
  theme(
    axis.text.x = element_text(hjust = 0.5, size=12, color="black"),
    axis.text.y = element_text(size=12, color="black"),
    axis.title = element_text(size = 14, color="black"),
                  legend.text =   element_text(size=12, color="black"),
                  legend.title = element_text(size = 12, color="black"),
    plot.title = element_text(size = 0, color="black"),
    legend.position = "none",
    strip.text = element_text(size=14,color='black')
        
  ) + plasmid_fill_scale + facet_wrap(~study)
 
C 
```

# B. percortion of plasmids over study periods
```{r}
df_plasmid_long <- df %>%
  separate_rows(carbapenemase_plasmid, sep = " & ") %>%   # split multi-genotypes
  group_by(isolate_no) %>%
  mutate(weight = 1 / n()) %>%               # fractional allocation
  ungroup()

df_plasmid_plot <- df_plasmid_long %>%
  group_by(study, carbapenemase_plasmid) %>%
  summarise(weighted_n = sum(weight), .groups = "drop") %>%
  group_by(study) %>%
  mutate(weighted_pct = 100 * weighted_n / sum(weighted_n))
 
df_plasmid_plot$carbapenemase_plasmid <-  factor(df_plasmid_plot$carbapenemase_plasmid,levels = plasmid_fill_scale$breaks)

B <-  ggplot(df_plasmid_plot  ,aes(x = study,stratum = carbapenemase_plasmid,alluvium = carbapenemase_plasmid,y=weighted_pct,fill = carbapenemase_plasmid)) +
  geom_alluvium(aes(fill = carbapenemase_plasmid),width=0.66,alpha=0.75) +
  geom_stratum(width=0.66,linewidth = 0.15) + theme_bw_me + xlab("Study") + ylab("Weighted percentage of isolates")  + theme(legend.position = "bottom",
                  axis.text =   element_text(size=12, color="black"),
                  axis.title = element_text(size = 14, color="black"),
                  legend.text =   element_text(size=8, color="black"),
                  legend.title = element_text(size = 10, color="black"),
                  plot.title = element_text(size = 14, color="black")) + scale_y_continuous(breaks = c(0,20,40,60,80,100)) +  plasmid_fill_scale + ggtitle("All isolates") 

B
```

# D. ST258 genomes
```{r}
df_long_plasmid_ST258 <- df  %>% subset(Species_ST == "Klebsiella pneumoniae ST258")  %>% 
  separate_rows(carbapenemase_plasmid, sep = " & ") %>%   # split multi-genotypes
  group_by(isolate_no) %>%
  mutate(weight = 1 / n()) %>%               # fractional allocation
  ungroup()

df_plot_plasmid_ST258 <- df_long_plasmid_ST258 %>%
  group_by(study, carbapenemase_plasmid) %>%
  summarise(weighted_n = sum(weight), .groups = "drop") %>%
  group_by(study) %>%
  mutate(weighted_pct = 100 * weighted_n / sum(weighted_n))
 
df_plot_plasmid_ST258$carbapenemase_plasmid <-  factor(df_plot_plasmid_ST258$carbapenemase_plasmid,levels = plasmid_fill_scale$breaks)

D <-  ggplot(df_plot_plasmid_ST258  ,aes(x = study,stratum = carbapenemase_plasmid,alluvium = carbapenemase_plasmid,y=weighted_pct,fill = carbapenemase_plasmid)) +
  geom_alluvium(aes(fill = carbapenemase_plasmid),width=0.66,alpha=0.75) +
  geom_stratum(width=0.66,linewidth = 0.15) + theme_bw_me + xlab("Study") + ylab("Percentage of isolates")  + theme(legend.position = "bottom",
                  axis.text =   element_text(size=12, color="black"),
                  axis.title = element_text(size = 14, color="black"),
                  legend.text =   element_text(size=8, color="black"),
                  legend.title = element_text(size = 10, color="black"),
                  plot.title = element_text(size = 14, color="black")) + scale_y_continuous(breaks = c(0,20,40,60,80,100)) +  plasmid_fill_scale+ ggtitle("ST258 isolates") 
  
D
```  

```{r,fig.width=9,fig.height=9} 
AB <-  cowplot::plot_grid(A,B + theme(legend.position = 'none') ,ncol=2,rel_widths = c(1,.33),labels = c("A","B"),label_size=14)  
CD <-  cowplot::plot_grid(C + theme(legend.position = 'none'),D + theme(legend.position = 'none'),ncol=2,labels = c("C","D"),label_size = 14,rel_widths = c(1,.33))

figure_3 <-  cowplot::plot_grid(AB,CD,ncol=1,rel_heights = c(1,1),labels = c("",""),label_size=14)  

figure_3
```

```{r}
ggsave(filename = "./figures/figure_3_carbapenemase_plasmids.png",plot=figure_3,width = 9,height = 9,dpi=900,bg = 'white')
```
