---
title: "Figure 3: Carbapenemase genotype comparison"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms')
```

# Environment

```{r}
# Packages
packages <- c("tidyverse","gridExtra","kableExtra","tableone","gontjesr","cowplot","ComplexHeatmap",'ggalluvial')
lapply(packages,library,character.only=T)

# Functions
source("./lib/consistent_themes.R")

# Print environment
Sys.info()
sessionInfo()
```

# Load data

```{r}
df <- readRDS("./data/dataset/CA_LTACH_first_clinical_per_quarter_CRKP_genomes_merged_studies_metadata.RDS")   
```

# Coordinate ST data

```{r} 
break_of_sts <-  c(sort(unique(df$Species_ST_recode %>% subset(.!="Singleton STs"))),"Singleton STs")
break_of_sts_renamed <- gsub("Klebsiella pneumoniae ","",break_of_sts)
       
ST_scale <- scale_fill_manual(breaks = break_of_sts,values = c(hues::iwanthue(n = length(unique(df$Species_ST_recode)) -1),"lightgray"),labels = break_of_sts_renamed,name = "Sequence type", guide = guide_legend(ncol=7, title.position = "top", label.position = "right"))

df$Species_ST_recode_no_species <- gsub("Klebsiella pneumoniae ","",df$Species_ST)
 
df_201415 <- df%>% subset(study == "2014-15")
df_202123<- df%>% subset(study == "2021-23")
```

# Load carbapenemase data
```{r}
carbapenemase_content <- readRDS("./data/carbapenemase_content/carbapenemase_content_merged_studies.RDS")
df <- left_join(df,carbapenemase_content)
```

# A. Fill being carbapenemase
```{r}
genotypes <- unique(df$carbapenemase) %>% sort
genotype_colors <- setNames(c(hues::iwanthue(length(genotypes)-1,hmin = 5,cmin = 5,lmin = 5),"gray"), genotypes)

genotype_scale <- scale_fill_manual(breaks = genotypes,values = genotype_colors,name = "Genotype", guide = guide_legend(ncol=4, title.position = "top", label.position = "right")) 

get_factor_order_carb <- function(ST_dist,var){
  new_order <- ST_dist %>% subset(study =='2021-23') %>% arrange(-n) %>% subset(n>0) %>% .[[var]] 
  zero_new_order_old <- ST_dist %>% subset(study =='2014-15') %>% subset(!get(var) %in% new_order) %>% arrange(-n) %>% .[[var]]
  c(c(new_order,zero_new_order_old) %>% subset(.!="No carbapenemase"),"No carbapenemase")
}

carb_dist <-  df  %>%
  count(study, carbapenemase) %>%
  complete(study, carbapenemase, fill = list(n = 0)) %>%
  group_by(study) %>%
  mutate(prop = n / sum(n) * 100)

df$carbapenemase <- factor(df$carbapenemase,levels = get_factor_order_carb(carb_dist,'carbapenemase'))
df <- df %>% arrange(carbapenemase)  

A <- ggplot(data=df,
       aes(y=carbapenemase, fill=carbapenemase)) +
  geom_bar()  + genotype_scale + facet_wrap(~study) +
  geom_text(stat='count',
            aes(label=..count..),
            hjust=-0.05, # push slightly to the right
            size=3.5)  +
  xlim(NA, 420.1) +
  theme_bw_me +
  xlab("Isolates") + ylab("") +
  theme(
    axis.text.x = element_text(hjust = 0.5, size=12, color="black"),
    axis.text.y = element_text(size=12, color="black"),
    axis.title = element_text(size = 14, color="black"),
                  legend.text =   element_text(size=12, color="black"),
                  legend.title = element_text(size = 12, color="black"),
    plot.title = element_text(size = 0, color="black"),
    legend.position = "none",
    strip.text = element_text(size=14,color='black')
  )

A
```


## C. Species ST
```{r} 
get_factor_order <- function(ST_dist,var){
  new_order <- ST_dist %>% subset(study =='2021-23') %>% arrange(-n) %>% subset(n>0) %>% .[[var]] 
  zero_new_order_old <- ST_dist %>% subset(study =='2014-15') %>% subset(!get(var) %in% new_order) %>% arrange(-n) %>% .[[var]]
  c(c(new_order,zero_new_order_old) %>% subset(.!="Singleton STs"),"Singleton STs")
}
 
ST_dist <-  df  %>%
  count(study, Species_ST_recode) %>%
  complete(study, Species_ST_recode, fill = list(n = 0)) %>%
  group_by(study) %>%
  mutate(prop = n / sum(n) * 100)
   
df$Species_ST_recode <- factor(df$Species_ST_recode,levels = get_factor_order(ST_dist,'Species_ST_recode'))

C <- ggplot(data=df,
       aes(y=Species_ST_recode, fill=carbapenemase)) +
  geom_bar() +
  xlim(NA, 220.1) +
  theme_bw_me +
  xlab("Isolates") + ylab("") +
  theme(
    axis.text.x = element_text(hjust = 0.5, size=12, color="black"),
    axis.text.y = element_text(size=12, color="black"),
    axis.title = element_text(size = 14, color="black"),
                  legend.text =   element_text(size=12, color="black"),
                  legend.title = element_text(size = 12, color="black"),
    plot.title = element_text(size = 0, color="black"),
    legend.position = "none",
    strip.text = element_text(size=14,color='black')) + genotype_scale + facet_wrap(~study)

C
```

# B. Compare carbapenemase genotypes between studies
```{r} 
ST_dist <-  df  %>%
  count(study, carbapenemase) %>%
  complete(study, carbapenemase, fill = list(n = 0)) %>%
  group_by(study) %>%
  mutate(prop = n / sum(n) * 100)
   
get_factor_order_carb <- function(ST_dist,var){
  new_order <- ST_dist %>% subset(study =='2021-23') %>% arrange(-n) %>% subset(n>0) %>% .[[var]] 
  zero_new_order_old <- ST_dist %>% subset(study =='2014-15') %>% subset(!get(var) %in% new_order) %>% arrange(-n) %>% .[[var]]
  c(c(new_order,zero_new_order_old) %>% subset(.!="No carbapenemase"),"No carbapenemase")
}
   
B <- ggplot(ST_dist %>% subset(n>0),aes(x = study,stratum = carbapenemase,alluvium = carbapenemase,y=prop,fill = carbapenemase)) +
  geom_alluvium(aes(fill = carbapenemase),width=0.66,alpha=0.75) +
  geom_stratum(width=0.66,linewidth = 0.2) + theme_bw_me + xlab("Study") + ylab("Percentage (%)") + genotype_scale + theme(legend.position = "bottom",
                  axis.text =   element_text(size=12, color="black"),
                  axis.title = element_text(size = 14, color="black"),
                  legend.text =   element_text(size=8, color="black"),
                  legend.title = element_text(size = 10, color="black"),
                  plot.title = element_text(size = 12, color="black")) + ggtitle("All isolates")

B
``` 

# D. Kpn ST258
```{r}
ST_dist_ST258 <-  df %>% subset(Species_ST == "Klebsiella pneumoniae ST258") %>%
  count(study, carbapenemase) %>%
  complete(study, carbapenemase, fill = list(n = 0)) %>%
  group_by(study) %>%
  mutate(prop = n / sum(n) * 100)
    

D <- ggplot(ST_dist_ST258 %>% subset(n>0),aes(x = study,stratum = carbapenemase,alluvium = carbapenemase,y=prop,fill = carbapenemase)) +
  geom_alluvium(aes(fill = carbapenemase),width=0.66,alpha=0.75) +
  geom_stratum(width=0.66,linewidth = 0.2) + theme_bw_me + xlab("Study") + ylab("Percentage (%)") + genotype_scale + theme(legend.position = "bottom",
                  axis.text =   element_text(size=12, color="black"),
                  axis.title = element_text(size = 14, color="black"),
                  legend.text =   element_text(size=8, color="black"),
                  legend.title = element_text(size = 10, color="black"),
                  plot.title = element_text(size = 12, color="black")) + ggtitle("ST258 isolates")

D
```

```{r,fig.width=9,fig.height=7.2} 
AB <-  cowplot::plot_grid(A,B + theme(legend.position = 'none') ,ncol=2,rel_widths = c(1,.33),labels = c("A","B"),label_size=12)  
CD <-  cowplot::plot_grid(C + theme(legend.position = 'none'),D + theme(legend.position = 'none'),ncol=2,labels = c("C","D"),label_size = 12,rel_widths = c(1,.33))

figure_3 <-  cowplot::plot_grid(AB,CD,ncol=1,rel_heights = c(1,1),labels = c("",""),label_size=12)  

figure_3
``` 

```{r}
ggsave(filename = "./figures/figure_3_carbapenemase.png", plot=figure_3, width = 9, height = 7.2, dpi=900, bg = 'white')
```
