---
title: "Figure 1: ST differences across studies"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/')
```

```{r}
# Packages
packages <- c("tidyverse","gridExtra","kableExtra","tableone","gontjesr","cowplot","ggalluvial")
lapply(packages,library,character.only=T)

# Functions
source("./Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms/lib/consistent_themes.R")

# Print environment
Sys.info()
sessionInfo()
```

```{r}
df <- readRDS("~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/2025-09-18_master_kpn_first_isolate_dataset_curation/results/CA_clinical_CRKP_first_isolate_metadata_091825.RDS")  
  
df$ST258 <- ifelse(df$Species_ST == "Klebsiella pneumoniae ST258",T,F)
df$ST17 <- ifelse(df$Species_ST == "Klebsiella pneumoniae ST17",T,F)

df$study <- factor(df$study,levels = c("2014-15","2021-23"))
df_201415 <- df%>% subset(study == "2014-15")
df_202123 <- df%>% subset(study == "2021-23")


df_202123_all <- readRDS("~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/2025-09-18_master_kpn_first_isolate_dataset_curation/results/CA_clinical_CRE_metadata_091825.RDS")  %>% subset(study == '2021-23')
```
# Coordinate ST data

```{r}
OLD_ST <- unique(df_201415$Species_ST) %>% sort
new_ST <- unique(df_202123$Species_ST) %>% sort 
ST_over_1 <- table(df$Species_ST) %>% subset(.>1) %>% names

df$Species_ST_new <- ifelse(df$Species_ST %in% c(ST_over_1),df$Species_ST,"Singleton STs") %>% gsub("Klebsiella pneumoniae ","",.)
                                          
break_of_sts <-  c(sort(unique(df$Species_ST_new %>% subset(.!="Singleton STs"))),"Singleton STs")
break_of_sts_renamed <- gsub("Klebsiella pneumoniae ","",break_of_sts)
       
ST_scale <- scale_fill_manual(breaks = break_of_sts,values = c(hues::iwanthue(n = length(unique(df$Species_ST_new)) -1),"lightgray"),labels = break_of_sts_renamed,name = "Sequence type", guide = guide_legend(ncol=7, title.position = "top", label.position = "right"))

df_201415 <- df%>% subset(study == "2014-15")
df_202123<- df%>% subset(study == "2021-23")
``` 

## A. Species ST
```{r}
A <- ggplot(data=df,
       aes(y=forcats::fct_infreq(Species_ST_new), fill=Species_ST_new)) +
  geom_bar() +
  geom_text(stat='count',
            aes(label=..count..),
            hjust=-0.05, # push slightly to the right
            size=3.5) + 
  xlim(NA, 325.1) +
  theme_bw_me +
  xlab("Count") + ylab("") +
  theme(
    axis.text.x = element_text(hjust = 1, size=12, color="black"),
    axis.text.y = element_text(size=12, color="black"),
    axis.title = element_text(size = 14, color="black"),
                  legend.text =   element_text(size=12, color="black"),
                  legend.title = element_text(size = 12, color="black"),
    plot.title = element_text(size = 0, color="black"),
    legend.position = "none",
    strip.text = element_text(size=14,color='black')
        
  ) + ST_scale + facet_wrap(~study)

A
```

# B. ST clinical Klebsiella alluvial plot comparisons
 
## ST level 

```{r} 
ST_dist <-  df  %>%
  count(study, Species_ST_new) %>%
  complete(study, Species_ST_new, fill = list(n = 0)) %>%
  group_by(study) %>%
  mutate(prop = n / sum(n) * 100)
   
ST_dist$Species_ST_new <- factor(ST_dist$Species_ST_new,levels = ST_dist %>% arrange(n) %>% group_by(Species_ST_new) %>% summarise (n = sum(n)) %>% arrange(-n) %>% .$Species_ST_new)

B <- ggplot(ST_dist %>% subset(n>0),aes(x = study,stratum = Species_ST_new,alluvium = Species_ST_new,y=prop,fill = Species_ST_new)) +
  geom_alluvium(aes(fill = Species_ST_new),width=0.66) +
  geom_stratum(width=0.66) + theme_bw_me + xlab("Study") + ylab("Percentage") + ST_scale + theme(legend.position = "bottom",
                  axis.text =   element_text(size=12, color="black"),
                  axis.title = element_text(size = 12, color="black"),
                  legend.text =   element_text(size=8, color="black"),
                  legend.title = element_text(size = 10, color="black"),
                  plot.title = element_text(size = 0, color="black")) + scale_y_continuous(breaks = c(0,20,40,60,80,100))
 
B
```

```{r}
paste0("No ST: ",length(unique(df_202123$Species_ST)))
gontjesr::convert_tableone_into_df(dataset=df_202123,vars='Species_ST')

paste0("Prior study No ST: ",length(unique(df_201415$Species_ST)))
gontjesr::convert_tableone_into_df(dataset=df_201415,vars='Species_ST')
```

# Overall figure

```{r,fig.width=9,fig.height=4.5}
AB <-  cowplot::plot_grid(A,B + theme(legend.position='none'),rel_widths =  c(1,.33),labels = c("A","B"),ncol=2)  
ST_scale_legend <- gontjesr::get_legend(B) 
ST_legend_plot <- cowplot::plot_grid(ST_scale_legend) + theme(plot.margin  = margin(t=0,unit='in'))
figure <- cowplot::plot_grid(AB ,ncol=1)
figure
```

```{r,fig.width=6,fig.height=4}   
ggsave(filename = "./Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms/figures/figure_1_taxonomy.png",plot=figure,width = 9,height = 4.5,dpi=900,bg = 'white')
```
