---
title: "figure_3_carbapenemase_plasmid"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/')
```

# Environment
```{r}
# Packages
packages <- c("tidyverse","gridExtra","kableExtra","cowplot","forcats","ggalluvial",'ComplexHeatmap')
lapply(packages,library,character.only=T)

# Functions
source("./Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms/lib/consistent_themes.R")

# Print environment
Sys.info()
sessionInfo() 
```

# Load data
```{r}
df <- readRDS("~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/2025-09-18_master_kpn_first_isolate_dataset_curation/results/CA_clinical_CRKP_first_isolate_metadata_091825.RDS")  

recode_LTACH_string <- sort(df$hospital_location) %>% unique %>% `names<-`(paste0("LTACH ",1:length(.))) %>% setNames(names(.), .)

df$hospital_location_recode <- dplyr::recode(df$hospital_location, !!! recode_LTACH_string)   %>% factor(.,levels =paste0("LTACH ",1:length(recode_LTACH_string)) )

df$study <- factor(df$study,levels = c("2014-15","2021-23"))

df_201415 <- df%>% subset(study == "2014-15")
df_202123 <- df%>% subset(study == "2021-23")
OLD_ST <- unique(df_201415$Species_ST) %>% sort
new_ST <- unique(df_202123$Species_ST) %>% sort 
ST_over_1 <- table(df$Species_ST) %>% subset(.>1) %>% names

df$Species_ST_new <- ifelse(df$Species_ST %in% c(ST_over_1),df$Species_ST,"Singleton STs") %>% gsub("Klebsiella pneumoniae ","",.)
 

df_202123_all <- readRDS("~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/2025-09-18_master_kpn_first_isolate_dataset_curation/results/CA_clinical_CRE_metadata_091825.RDS")  %>% subset(study == '2021-23')

df_201415 <- df%>% subset(study == "2014-15")
df_202123 <- df%>% subset(study == "2021-23")

number_of_weeks_1415 <- as.numeric(round(difftime(max(df_201415$date,na.rm = T),min(df_201415$date,na.rm = T),units = 'weeks')) + 1)
number_of_weeks_2123 <- as.numeric(round(difftime(max(df_202123_all$date,na.rm = T),min(df_202123_all$date,na.rm = T),units = 'weeks')) + 1)
```

# Mobsuite data
## INTEGRATE
```{r}  
mobsuite_contig <- read_delim("~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Descriptive_epidemiology/2024-12-30_mobsuite/results/INTEGRATE_contig_report.txt")
mobsuite_contig$isolate_no <- gsub(".fna","",mobsuite_contig$sample_id) 
mobsuite_contig <- subset(mobsuite_contig,isolate_no %in% df$isolate_no)
mobtyper <- read_delim("~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Descriptive_epidemiology/2024-12-30_mobsuite/results/INTEGRATE_mobtyper_results.txt")
mobtyper$isolate_no <-mobtyper$sample_id %>% str_split(.,":",simplify=T) %>% .[,1] %>%  gsub(".fna","",.)
mobtyper <- subset(mobtyper,isolate_no %in% df$isolate_no)
```
## 2014-15 study
```{r}
amrfinder_mat <- readRDS("~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/2025-09-18_master_kpn_first_isolate_dataset_curation/results/amrfinder_matrix_091825.RDS")
amrfinder_mat <- subset(amrfinder_mat,rownames(amrfinder_mat) %in% df$isolate_no)
amrfinder <- readRDS("~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/2025-09-18_master_kpn_first_isolate_dataset_curation/results/amrfinder_cleaned_091825.RDS")
amrfinder_carb <- subset(amrfinder,subclass == "CARBAPENEM") %>% subset(isolate_no %in% df$isolate_no)
mobtyper_old <-  read_delim("~/Desktop/gl_nfs/Project_Penn_KPC/Analysis/Combination_resistance/pre-intro-blbli-resistance-ms/data/mobsuite/CRKP_mobtyper_results.txt")
mobtyper_old$isolate_no <-mobtyper_old$sample_id %>% str_split(.,":",simplify=T) %>% .[,1] %>%  gsub("_contigs_l1000","",.)
mobtyper_old <- subset(mobtyper_old,isolate_no %in% df$isolate_no)
mobsuite_contig_old <-  read_delim("~/Desktop/gl_nfs/Project_Penn_KPC/Analysis/Combination_resistance/pre-intro-blbli-resistance-ms/data/mobsuite/CRKP_contig_report.txt")
mobsuite_contig_old$isolate_no <-mobsuite_contig_old$sample_id %>% str_split(.,":",simplify=T) %>% .[,1] %>%  gsub("_contigs_l1000","",.)
mobsuite_contig_old <- subset(mobsuite_contig_old,isolate_no %in% df$isolate_no)

mobtyper_merged <- bind_rows(mobtyper_old %>% select(isolate_no,num_contigs,size,gc,primary_cluster_id,mash_nearest_neighbor),
                             mobtyper %>% select(isolate_no,num_contigs,size,gc,primary_cluster_id,mash_nearest_neighbor)) %>% mutate(study =ifelse( grepl("INT",isolate_no),"2021-23",'2014-15'))
mobsuite_contig_merged <- bind_rows(mobsuite_contig_old %>% select(isolate_no,contig_id,size,gc,primary_cluster_id,mash_nearest_neighbor),
                             mobsuite_contig %>% select(isolate_no,contig_id,size,gc,primary_cluster_id,mash_nearest_neighbor))%>% mutate(study =ifelse( grepl("INT",isolate_no),"2021-23",'2014-15'))
mobtyper_mat <- gontjesr::get_mobtyper_cluster_matrix(df,mobtyper_merged)
```




KPC plasmid matrix
```{r}
get_KPC_plasmid <- function(isolate,amrfinder_carb,mobsuite_contig){
  amrfinder_sub <- amrfinder_carb %>% subset(isolate_no == isolate)
  mobsuite_contig_merged <- mobsuite_contig_merged %>% subset(isolate_no == isolate & contig_id %in% amrfinder_sub$contig_id)
  mobsuite_contig_merged$primary_cluster_id %>% paste0(collapse=';') %>% {ifelse(.=="","No carbapenemase",.)} %>% {ifelse(.=="-","Chromosome",.)}
}


df$KPC_plasmid <- lapply(df$isolate_no,get_KPC_plasmid,amrfinder_carb,mobsuite_contig) %>% unlist

mobtyper_merged$KPC_plasmid <- apply(mobtyper_merged,1,FUN=function(x){
  isolate_kpc <- df %>% subset(isolate_no == x[['isolate_no']]) %>% .$KPC_plasmid %>% str_split(.,";" ) %>% unlist
  sum(x[['primary_cluster_id']] %in% isolate_kpc) 
})

mobtyper_merged$carbapenemase <-apply(mobtyper_merged,1,FUN=function(x){
  mobsuite_contigs <- mobsuite_contig_merged %>% subset(primary_cluster_id == x[["primary_cluster_id"]] & isolate_no == x[["isolate_no"]] ) %>% .$contig_id
  amrfinder_sub <- amrfinder_carb %>% subset(contig_id %in% mobsuite_contigs)
  if(nrow(amrfinder_sub)==0){
    ""
  } else{
    
  paste0(amrfinder_sub$element_symbol_renamed,collapse=';')
  }
   
})

df_202123<- df%>% subset(study == "2021-23")

# Convert KPC_plasmid variable into a matrix where row is isolate and entry is 1 for present and 0 for absent
KPC_plasmid_matrix <- df_202123 %>% select(isolate_no,KPC_plasmid) %>% 
    pivot_wider(names_from = KPC_plasmid, values_from = KPC_plasmid) %>%     column_to_rownames("isolate_no")  %>% {ifelse(is.na(.),0,1)}  %>% as.data.frame
```

# A. KPC plasmids
```{r}
KPC_plasmids <- c(mobtyper_merged  %>% subset(KPC_plasmid ==1) %>% .$primary_cluster_id %>% unique %>% sort)
plasmid_fill <- scale_fill_manual(breaks = c(KPC_plasmids,"Chromosome","No carbapenemase"),values = c(hues::iwanthue(length(KPC_plasmids)),"darkgray",'lightgray'),name="Carbapenemase-containing plasmid",guide = guide_legend(title.position = "top", label.position = "right"))

A <- ggplot(data=df ,aes(y=forcats::fct_infreq(KPC_plasmid),fill=KPC_plasmid)) + geom_bar(stat='count')  + theme_bw_me + ylab("") + labs(fill="KPC_plasmid") + facet_wrap(~study) + plasmid_fill  + xlab("Isolates") + theme(legend.position = 'none') +
  geom_text(stat='count',
            aes(label=..count..),
            hjust=-0.05, 
            size=3.5)  + xlim(NA,95.1) +
  theme(
    axis.text.x = element_text(hjust = 0.5, size=12, color="black"),
    axis.text.y = element_text(size=12, color="black"),
    axis.title = element_text(size = 14, color="black"),
                  legend.text =   element_text(size=12, color="black"),
                  legend.title = element_text(size = 12, color="black"),
    plot.title = element_text(size = 0, color="black"),
    legend.position = "none",
    strip.text = element_text(size=14,color='black')
        
  )
A
```

## C. . Species ST
```{r} 
C <- ggplot(data=df,
       aes(y=forcats::fct_infreq(Species_ST_new), fill=KPC_plasmid)) +
  geom_bar() +
  xlim(NA, 310.1) +
  theme_bw_me +
  xlab("Isolates") + ylab("") +
  theme(
    axis.text.x = element_text(hjust = 0.5, size=12, color="black"),
    axis.text.y = element_text(size=12, color="black"),
    axis.title = element_text(size = 14, color="black"),
                  legend.text =   element_text(size=12, color="black"),
                  legend.title = element_text(size = 12, color="black"),
    plot.title = element_text(size = 0, color="black"),
    legend.position = "none",
    strip.text = element_text(size=14,color='black')
        
  ) + plasmid_fill + facet_wrap(~study)

C
```

# B. Proportion of plasmids over study periods
```{r}
mobtyper_prop <-  df   %>%
  count(study, KPC_plasmid) %>%
  complete(study, KPC_plasmid, fill = list(n = 0)) %>%
  group_by(study) %>%
  mutate(prop = n / sum(n) * 100)
   
mobtyper_prop$KPC_plasmid <- factor(mobtyper_prop$KPC_plasmid,levels = mobtyper_prop %>% arrange(n) %>% group_by(KPC_plasmid) %>% summarise (n = sum(n)) %>% arrange(-n) %>% .$KPC_plasmid)
 
B <-  ggplot(mobtyper_prop  ,aes(x = study,stratum = KPC_plasmid,alluvium = KPC_plasmid,y=prop,fill = KPC_plasmid)) +
  geom_alluvium(aes(fill = KPC_plasmid),width=0.5) +
  geom_stratum(width=0.5) + theme_bw_me + xlab("Study") + ylab("Percentage")  + theme(legend.position = "bottom",
                  axis.text =   element_text(size=12, color="black"),
                  axis.title = element_text(size = 14, color="black"),
                  legend.text =   element_text(size=8, color="black"),
                  legend.title = element_text(size = 10, color="black"),
                  plot.title = element_text(size = 12, color="black")) + scale_y_continuous(breaks = c(0,20,40,60,80,100)) +  plasmid_fill+ ggtitle("All isolates") 

B
```

# D. 
```{r}
ST258_genomes <- df %>% subset(ST=="258") %>% .$isolate_no
mobtyper_prop_ST258 <-  df %>% subset(ST=="258")   %>%
  count(study, KPC_plasmid) %>%
  complete(study, KPC_plasmid, fill = list(n = 0)) %>%
  group_by(study) %>%
  mutate(prop = n / sum(n) * 100)
   
mobtyper_prop_ST258$KPC_plasmid <- factor(mobtyper_prop_ST258$KPC_plasmid,levels = mobtyper_prop %>% arrange(n) %>% group_by(KPC_plasmid) %>% summarise (n = sum(n)) %>% arrange(-n) %>% .$KPC_plasmid)
 
 
D <-  ggplot(mobtyper_prop_ST258  ,aes(x = study,stratum = KPC_plasmid,alluvium = KPC_plasmid,y=prop,fill = KPC_plasmid)) +
  geom_alluvium(aes(fill = KPC_plasmid),width=0.5) +
  geom_stratum(width=0.5) + theme_bw_me + xlab("Study") + ylab("Percentage")  + theme(legend.position = "bottom",
                  axis.text =   element_text(size=12, color="black"),
                  axis.title = element_text(size = 14, color="black"),
                  legend.text =   element_text(size=8, color="black"),
                  legend.title = element_text(size = 10, color="black"),
                  plot.title = element_text(size = 12, color="black")) + scale_y_continuous(breaks = c(0,20,40,60,80,100)) +  plasmid_fill + ggtitle("ST258 isolates") 
D
```  

```{r,fig.width=9,fig.height=9}  
AB <-  cowplot::plot_grid(A,B + theme(legend.position = 'none') ,ncol=2,rel_widths = c(1,.33),labels = c("A","B"),label_size=12)  
CD <-  cowplot::plot_grid(C + theme(legend.position = 'none'),D + theme(legend.position = 'none'),ncol=2,labels = c("C","D"),label_size = 12,rel_widths = c(1,.33))
figure_3 <-  cowplot::plot_grid(AB,CD,ncol=1,rel_heights = c(1,1),labels = c("",""),label_size=12)  
figure_3
```

```{r}
ggsave(filename = "./Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms/figures/figure_3_carbapenemase_plasmids.png",plot=figure_3,width = 9,height = 9,dpi=900,bg = 'white')
```

