---
title: "Supplemental figure 5: Genotype on phylogeny"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms')
```

# Environment 

```{r}
# Packages
packages <- c("tidyverse","gridExtra","kableExtra","tableone","cowplot","ComplexHeatmap",'ggalluvial','ape','ggtree','ggtext')
lapply(packages,library,character.only=T)

# Functions
source("./lib/consistent_themes.R") 
source("./lib/common_functions.R") 

# Print environment
Sys.info()
sessionInfo()
```

# Load data

```{r}
df <- readRDS("./data/dataset/CA_LTACH_first_clinical_per_quarter_CRKP_genomes_merged_studies_metadata.RDS")   
   
df_201415 <- df%>% subset(study == "2014-15")
df_202123 <- df%>% subset(study == "2021-23") 
```

# Load  carbapenemase content
```{r}
carbapenemase_content <- readRDS("./data/carbapenemase_content/carbapenemase_content_merged_studies.RDS")
df <- left_join(df,carbapenemase_content)

df$carbapenemase_md <- format_carbapenemase(df$carbapenemase) 
```

# Load omp matrix
```{r}
carb_omp <-  readRDS("./data/carbapenemase_content/carbapenem_resistance_genotype_content_merged_first_clinical_CRKP_isolate_per_quarter.RDS")
``` 

# Load phylogeny 
```{r}
tr <- read.tree("./data/phylogeny/INTEGRATE/INTEGRATE_CRKP.treefile") 
```

# INTEGRATE dataset for figure
```{r,fig.width=9.5,height=6.7857}  
df_carb_omp <- df %>% select(isolate_no,carbapenemase,carbapenemase_md,study,Species_ST_recode) %>% left_join(., carb_omp %>% mutate(isolate_no = rownames(.)))
df_carb_omp <- subset(df_carb_omp,isolate_no %in% tr$tip.label)
df_carb_omp <- df_carb_omp %>% as.data.frame
rownames(df_carb_omp) <- df_carb_omp$isolate_no 
```

# Create phylogeny
```{r,fig.width=11,fig.height=11}  
geno_vars <- colnames(df_carb_omp) %>% subset(!.%in% c("study","Species_ST_recode","isolate_no","carbapenemase","carbapenemase_md"))
genotype_heatmap <- df_carb_omp %>% select(geno_vars) %>% drop_na() %>% select_if(colSums(.)>0) %>% ComplexHeatmap::Heatmap()  

genotype_matrix <- df_carb_omp %>% select(genotype_heatmap@column_names_param$labels[ComplexHeatmap::column_order(genotype_heatmap)]) %>% mutate_all(as.factor) 
colnames(genotype_matrix) <-  recode_genotypes(colnames(genotype_matrix))
```

```{r,fig.width=9.75,fig.height=9.75}  
# Sequence type
p0 <- gheatmap(ggtree(tr),df_carb_omp %>% select(Species_ST_recode) %>% `colnames<-`("Sequence type (ST)"),color = NULL,width=0.05,colnames_position = 'top',colnames_angle = 90,hjust=0, colnames_offset_y = 0.25) + ST_scale_3_row +  theme(legend.key = element_rect(colour = c('black')))

p0.1 <- p0 + ggnewscale::new_scale_fill()

# Carbapenemase markdown
p1 <- gheatmap(p0.1,df_carb_omp %>% select(carbapenemase_md) %>% `colnames<-`("Carbapenemase"),color = NULL,width=0.05,offset=0.0035,colnames_position = 'top',colnames_angle = 90,hjust=0, colnames_offset_y = 0.25)  + carbapenemase_scale_4_row + theme(legend.key = element_rect(colour = c('black')))

p1.1 <- p1 + ggnewscale::new_scale_fill()

# Genotype matrix
figure <- gheatmap(p1.1,genotype_matrix, color  = NULL,width=0.05*length(geno_vars), offset=0.007, colnames_position = 'top', colnames_angle = 90, hjust=0, colnames_offset_y = 0.25)  + feature_scale + ylim(NA,620) + theme(legend.position = 'bottom',legend.direction="horizontal",  legend.justification = "center", legend.key = element_rect(colour = c('black')),legend.text=element_markdown()) + geom_treescale(y = -11, offset = 2)

figure_legend <- cowplot::get_legend(figure + theme(legend.key.size = unit(0.5,"cm")))

final_figure <- cowplot::plot_grid(figure + theme(legend.position = 'none',
                                                  plot.margin = margin(b=-24)),figure_legend,ncol=1,rel_heights = c(1,0.15))
final_figure
```

# Save figure
```{r}
ggsave(filename = "./figures/s_figure_5_carbapenem_resistance_associated_genotypes_phylogeny.png",plot=final_figure, width = 9.75,height = 9.75, dpi=900, bg = 'white', unit = 'in')
``` 
