---
title: "Supplemental Figure 15: 2021-23 phylogeny with resistance"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms')
```

# Environment

```{r}
# Packages
packages <- c("tidyverse","gridExtra","kableExtra","tableone","cowplot","ComplexHeatmap",'ggalluvial','ape','ggtree','phytools')
lapply(packages,library,character.only=T)

# Functions
source("./lib/consistent_themes.R")

# Print environment
Sys.info()
sessionInfo()
```

# Load data

```{r}
df <- readRDS("./data/dataset/CA_LTACH_first_clinical_per_quarter_CRKP_genomes_merged_studies_metadata.RDS") %>% subset(study == "2021-23")  

MIC_variables <- c('MERO',"IMI",'blbli','MVB','IR','CZA',"FDC","CT","OMC","ERV","DLX","CST","PLZ","FOS") 
resistance_vars <- paste0(MIC_variables,"_dich_num")  
```

```{r}
carbapenemase_content <- readRDS("./data/carbapenemase_content/carbapenemase_content_merged_studies.RDS")
df <- left_join(df,carbapenemase_content)
df$carbapenemase_md <- format_carbapenemase(df$carbapenemase) 
```

# Tree
```{r}
tr <- read.tree("./data/phylogeny/INTEGRATE/INTEGRATE_CRKP.treefile") 
``` 

# Clustering of resistance
```{r,fig.width=13,fig.height=15}  
resistance_clustering <-df %>% subset(isolate_no %in% tr$tip.label) %>% select(resistance_vars) %>% drop_na() %>% pheatmap()
```

# Phylogeny
```{r}
get_short_phylogeny <- function(tr,df,col_width,col_offset,col_offset_y,col_fontsize,ylimit,treescale_y,treescale_offset,resistance_variable_order){
  df <- as.data.frame(df)
  rownames(df) <- df$isolate_no
  # ST 
  p0 <- gheatmap(ggtree(tr),df %>% select(Species_ST_recode) %>% `colnames<-`("Sequence type"),color = NULL,width=col_width,colnames_position = 'top',colnames_angle = 90,hjust=0, colnames_offset_y = col_offset_y,font.size = col_fontsize) + ST_scale_3_row  + phylo_theme+  ggnewscale::new_scale_fill() 
  # Carbapenemase
  p1 <- gheatmap(p0,df %>% select(carbapenemase_md) %>% `colnames<-`("Carbapenemase"),color = NULL,width=col_width,offset=col_offset,colnames_position = 'top',colnames_angle = 90,hjust=0, colnames_offset_y = col_offset_y,font.size = col_fontsize)  + carbapenemase_scale  + phylo_theme + ggnewscale::new_scale_fill() 
  # Resistance
  resistance_matrix <- df[,resistance_variable_order] %>% mutate_all(as.factor)
  colnames(resistance_matrix) <- recode_resistance_variables(colnames(resistance_matrix))

  figure <-  gheatmap(p1,resistance_matrix,color = NULL,width=col_width*length(resistance_variable_order),offset=col_offset*2,colnames_position = 'top',colnames_angle = 90,hjust=0, colnames_offset_y = col_offset_y,font.size = col_fontsize)  + resistance_bin_scale + ylim(NA,ylimit) + geom_treescale(y = -treescale_y,offset=treescale_offset)
  
  figure
  
}
```

```{r,fig.width=8.5,fig.height=10.625} 
# Legend theme
phylo_theme <-  theme(legend.position = 'bottom',
                               legend.justification = "center", legend.key = element_rect(colour = c('black')),
                               legend.box.spacing = unit(.00001, "cm"),
                               legend.key.size = unit(0.4, "cm"),legend.key.width = unit(0.4, "cm") ,
                               legend.title = element_text(size=14),legend.text = element_markdown(size=12),
                               legend.title.align=0.5,legend.text.align = 0,
                               legend.margin=margin(t=-0.5,r=0,b=0,l=0,unit="cm"),legend.spacing.x=unit(.25, "cm")
                               ) 

# Order of variables
resistance_variable_order <- resistance_vars[column_order(resistance_clustering)]
```

## Overall

```{r,fig.width=8.5,fig.height=10.625} 
A <- get_short_phylogeny(df = df ,tr =  tr,col_width = 0.1,col_offset = 0.0065,col_offset_y =  0.25,col_fontsize = 3,ylimit = 565,treescale_y = 10,treescale_offset = 2,resistance_variable_order = resistance_variable_order) + phylo_theme

A+ theme(legend.position= 'none')
```

## ST258

```{r,fig.width=3.75,fig.height=5}
st258_df <- df %>% subset(ST=='ST258')
st258_df <- as.data.frame(st258_df)
rownames(st258_df) <- st258_df$isolate_no
tr_ST258 <- tr %>% keep.tip(subset(st258_df$isolate_no,st258_df$isolate_no %in% tr$tip.label) ) %>% phytools::midpoint.root()

B <- get_short_phylogeny(df = st258_df ,tr =  tr_ST258,col_width =  0.05,col_offset =  0.000076,col_offset_y = 0.25,col_fontsize = 2.5,ylimit = 267.5,treescale_y = 6.5,treescale_offset = 1.33,resistance_variable_order = resistance_variable_order) + theme(legend.position = 'none')

B   + theme(legend.position= 'none')
```

## ST14

```{r,fig.width=3.75,fig.height=5}
st14_df <- df %>% subset(ST=='ST14')
st14_df <- as.data.frame(st14_df)
rownames(st14_df) <- st14_df$isolate_no
tr_ST14 <- tr %>% keep.tip(subset(st14_df$isolate_no,st14_df$isolate_no %in% tr$tip.label) )%>% phytools::midpoint.root()

C <- get_short_phylogeny(df = st14_df ,tr =  tr_ST14,col_width =  0.05,col_offset =  0.00002,col_offset_y = 0.1,col_fontsize = 2.5,ylimit = 177.5,treescale_y = 6,treescale_offset = 1.2,resistance_variable_order = resistance_variable_order)  + theme(legend.position = 'none')

C + theme(legend.position = 'none')
```

## ST307

```{r,fig.width=3.75,fig.height=5}
st307_df <- df %>% subset(ST=='ST307')
st307_df <- as.data.frame(st307_df)
rownames(st307_df) <- st307_df$isolate_no
tr_ST307 <- tr %>% keep.tip(subset(st307_df$isolate_no,st307_df$isolate_no %in% tr$tip.label) )%>% phytools::midpoint.root()

D <- get_short_phylogeny(df = st307_df ,tr =  tr_ST307,col_width =  0.05,col_offset =  0.000022,col_offset_y = -0.4,col_fontsize = 2.5,ylimit = 45,treescale_y = 0.75,treescale_offset = 0.3,resistance_variable_order = resistance_variable_order)  + theme(legend.position = 'none')
 
D + theme(legend.position = 'none')
```

## ST17

```{r,fig.width=3.75,fig.height=5}
st17_df <- df %>% subset(ST=='ST17')
st17_df <- as.data.frame(st17_df)
rownames(st17_df) <- st17_df$isolate_no
tr_ST17 <- tr %>% keep.tip(subset(st17_df$isolate_no,st17_df$isolate_no %in% tr$tip.label)) %>% phytools::midpoint.root()

E <- get_short_phylogeny(df = st17_df ,tr =  tr_ST17,col_width =  0.05,col_offset =  0.000008,col_offset_y = -0.4,col_fontsize = 2.5,ylimit = 42,treescale_y = 0.8,treescale_offset = 0.3,resistance_variable_order = resistance_variable_order)  + theme(legend.position = 'none')
 
E 
```

# Combine figures

```{r,fig.width=11.25,fig.height=11.25}
A_fig <- cowplot::plot_grid(A + theme(legend.position='none'),labels = c("A"))
A_legend <- cowplot::get_legend(A)
legend_fig <- cowplot::plot_grid(A_legend)
smaller <- cowplot::plot_grid(B,C,D,E,ncol=2,labels = c("B","C","D","E"),hjust = 0)
merged <- cowplot::plot_grid(A_fig,smaller,ncol=2,rel_widths = c(0.5,1))
figure <- cowplot::plot_grid(merged,A_legend,rel_heights = c(1,0.09),ncol=1)
figure
```

```{r,fig.width=13,fig.height=16}   
ggsave(filename = "./figures/s_figure_15_resistance_phylogeny.png", plot=figure, width = 11.25, height = 11.25, dpi=900,bg = 'white')
```