---
title: "Supplemental Figure 1: Repeated sampling"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms')
```

# Environment

```{r}
# Packages
packages <- c("tidyverse","cowplot",'ggalluvial')
lapply(packages,library,character.only=T)

# Functions
source("./lib/consistent_themes.R")

# Print environment
Sys.info()
sessionInfo()
```

# Load data 

```{r}
df <- readRDS("./data/dataset/CA_LTACH_clinical_CRKP_genomes_merged_studies_metadata.RDS")  
df_first_per_quarter <- readRDS("./data/dataset/CA_LTACH_first_clinical_per_quarter_CRKP_genomes_merged_studies_metadata.RDS")
 
df_201415 <- df%>% subset(study == "2014-15")
df_202123 <- df%>% subset(study == "2021-23")
```

# A. Total number of isolates per patient

```{r}
df_summary <- df %>% group_by(study,participant_id) %>% summarise(n_isolates = length(isolate_no))

df_summary_proportion <-  df_summary %>% group_by(study,n_isolates) %>% summarise(n=length(participant_id))  
n_participants_1415 <- df_201415$participant_id %>% n_distinct()
n_participants_2123 <- df_202123$participant_id %>% n_distinct()

df_summary_proportion$percentage <- ifelse(df_summary_proportion$study=='2014-15',df_summary_proportion$n /n_participants_1415, df_summary_proportion$n / n_participants_2123) * 100

wilcox.test(n_isolates ~ study, df_summary)

A <- ggplot(data=df_summary_proportion,aes(x=n_isolates,y=percentage)) + geom_bar(stat='identity',fill='black') + facet_wrap(~study) + theme_bw_me + ylab("Percentage of patients (%)") + xlab("Clinical isolates per patient") + ylim(NA,100) + geom_text(aes(x=n_isolates,label = n,y=percentage+5),size = 2.75)  + scale_x_continuous(breaks = scales::pretty_breaks(10))

A
```

# B - Total number of isolates when restricted to one isolate

```{r}
df_summary_first_per_q <- df %>% subset(first_isolate_per_quarter==T) %>% group_by(study,participant_id) %>% summarise(n_isolates = length(isolate_no))

df_summary_first_per_q_prop <-  df_summary_first_per_q %>% group_by(study,n_isolates) %>% summarise(n=length(participant_id))  

df_summary_first_per_q_prop$percentage <- ifelse(df_summary_first_per_q_prop$study=='2014-15',df_summary_first_per_q_prop$n /n_participants_1415, df_summary_first_per_q_prop$n / n_participants_2123) * 100

wilcox.test(n_isolates ~ study, df_summary_first_per_q)

B <- ggplot(data=df_summary_first_per_q_prop,aes(x=n_isolates,y=percentage)) + geom_bar(stat='identity',fill = 'black') + theme_bw_me + ylab("Percentage of patients (%)") + xlab("Quarters with at least one isolate") + ylim(NA,100) + geom_text(aes(x=n_isolates,label = n,y=percentage+5),size = 3.5)  + facet_wrap(~study) + scale_x_continuous(breaks = scales::pretty_breaks(5))

B
```

# C. Sequence types per patient

```{r}
df_summary_ST <- df %>% group_by(study,participant_id) %>% summarise(n_STs = n_distinct(Species_ST))

df_summary_ST_prop <-  df_summary_ST %>% group_by(study,n_STs) %>% summarise(n=length(n_STs))  

df_summary_ST_prop$percentage <- ifelse(df_summary_ST_prop$study=='2014-15',df_summary_ST_prop$n /n_participants_1415, df_summary_ST_prop$n / n_participants_2123) * 100
df_summary_ST_prop$n_STs <- as.factor(df_summary_ST_prop$n_STs)

C <- ggplot(data=df_summary_ST_prop,aes(x=n_STs,y=percentage)) + geom_bar(stat='identity',fill = 'black') + theme_bw_me + ylab("Percentage of patients (%)") + xlab("Sequence types per patient\n") + ylim(NA,104) + geom_text(aes(x=n_STs,label = n,y=percentage+4),size = 3.5)  + facet_wrap(~study)
C
```

# D. Sequence type

```{r}
df_summary_ST_first_per_q <- df %>% subset(first_isolate_per_quarter==T) %>% group_by(study,participant_id) %>% summarise(n_STs = n_distinct(Species_ST))

df_summary_ST_first_per_q_prop <-  df_summary_ST_first_per_q %>% group_by(study,n_STs) %>% summarise(n=length(n_STs))  

df_summary_ST_first_per_q_prop$percentage <- ifelse(df_summary_ST_first_per_q_prop$study=='2014-15',df_summary_ST_first_per_q_prop$n /n_participants_1415, df_summary_ST_first_per_q_prop$n / n_participants_2123) * 100
df_summary_ST_first_per_q_prop$n_STs <- as.factor(df_summary_ST_first_per_q_prop$n_STs)

D <- ggplot(data=df_summary_ST_first_per_q_prop,aes(x=n_STs,y=percentage)) + geom_bar(stat='identity',fill = 'black') + theme_bw_me + ylab("Percentage of patients (%)") + xlab("Sequence types per patient\n(First isolate per patient per quarter)") + ylim(NA,104) + geom_text(aes(x=n_STs,label = n,y=percentage+4),size = 3.5)  + facet_wrap(~study)
D
```

# E -  Frequency per patient
```{r}
frequency_per_ST <- df %>%
    group_by(study, participant_id, ST) %>%
    summarise(n_isolates = n(), .groups = "drop") %>%
    count(study, ST, n_isolates, name = "n_participants") %>%
    group_by(study, ST) %>%
    mutate(
        perc_participants = 100 * n_participants / sum(n_participants)
    ) %>%
    ungroup()

frequency_per_ST$ST <- factor(frequency_per_ST$ST,levels = frequency_per_ST %>% group_by(ST) %>% summarise(n_isolates = sum(n_isolates)) %>% arrange(-n_isolates) %>% .$ST)
frequency_per_ST$n_isolates <- factor(
  frequency_per_ST$n_isolates,
  levels = sort(unique(frequency_per_ST$n_isolates))
) 

E <- ggplot(frequency_per_ST,
       aes(x = n_isolates,
           y = ST,
           fill = perc_participants)) +
    geom_tile() +
    facet_wrap(~study) + geom_text(aes(label = round(perc_participants,1)),color='black',size = 2) + theme_bw_me + xlab("Number of contributed isolates") + ylab("Sequence type (ST)") + scale_fill_gradient(breaks = c(0,20,40,60,80,100),low = 'white',high='red',name = 'Percentage of patients (%)')
```


# F - Change in study prevalence based on study method 
```{r}
get_frequency_differences <- function(df,study){
  df_first_isolate <- df %>% subset(first_isolate==T)
  df_first_isolate_per_quarter <- df %>% subset(first_isolate_per_quarter==T)

df_ST_dist <-   df   %>%
  count(ST) %>%
  complete(ST, fill = list(n = 0)) %>%
  mutate(prop = n / sum(n) * 100)  %>% rename('n_overall' = 'n',
                                                                                   'prop_overall' = 'prop')

df_first_isolate_ST_Dist <-   df_first_isolate   %>%
  count(ST) %>%
  complete(ST, fill = list(n = 0)) %>%
  mutate(prop = n / sum(n) * 100)%>% rename('n_first' = 'n',
                                                                                   'prop_first' = 'prop')
df_first_isolate_per_q_ST_Dist <-   df_first_isolate_per_quarter   %>%
  count(ST) %>%
  complete(ST, fill = list(n = 0)) %>%
  mutate(prop = n / sum(n) * 100)  %>% rename('n_quarter' = 'n',
                                                                                   'prop_quarter' = 'prop')

df_ST_dist_by_study <- left_join(df_ST_dist,df_first_isolate_ST_Dist) %>% left_join(df_first_isolate_per_q_ST_Dist)
df_ST_dist_by_study[is.na(df_ST_dist_by_study)] <- 0

df_ST_dist_by_study$n_overall_minus_first <- df_ST_dist_by_study$n_overall - df_ST_dist_by_study$n_first
df_ST_dist_by_study$n_overall_minus_quarter <- df_ST_dist_by_study$n_overall - df_ST_dist_by_study$n_quarter
df_ST_dist_by_study$n_quarter_minus_first <- df_ST_dist_by_study$n_quarter - df_ST_dist_by_study$n_first

df_ST_dist_by_study$prop_overall_minus_first <- df_ST_dist_by_study$prop_overall - df_ST_dist_by_study$prop_first
df_ST_dist_by_study$prop_overall_minus_quarter <- df_ST_dist_by_study$prop_overall - df_ST_dist_by_study$prop_quarter
df_ST_dist_by_study$prop_quarter_minus_first <- df_ST_dist_by_study$prop_quarter - df_ST_dist_by_study$prop_first

df_ST_dist_by_study$prop_overall_div_first <- df_ST_dist_by_study$prop_overall / df_ST_dist_by_study$prop_first
df_ST_dist_by_study$prop_overall_div_quarter <- df_ST_dist_by_study$prop_overall / df_ST_dist_by_study$prop_quarter
df_ST_dist_by_study$prop_quarter_div_first <- df_ST_dist_by_study$prop_quarter / df_ST_dist_by_study$prop_first

reshaped_dataset <- reshape2::melt(df_ST_dist_by_study,id.var='ST')
reshaped_dataset$variable <- recode(reshaped_dataset$variable,                                                                  'prop_overall_minus_first' = "First isolate per patient",                                                                       'prop_overall_minus_quarter' = "First isolate per patient per quarter"  )

reshaped_dataset_of_interest <- reshaped_dataset %>% subset(variable %in% c("First isolate per patient","First isolate per patient per quarter")) 

reshaped_dataset_of_interest$variable <- factor(reshaped_dataset_of_interest$variable,levels = c("First isolate per patient per quarter","First isolate per patient"))
reshaped_dataset_of_interest$study <- study
return(reshaped_dataset_of_interest)
}

df_overall_diff <- get_frequency_differences(df,"overall")
df_201415_diff <- get_frequency_differences(df_201415,"2014-15")
df_202123_diff <- get_frequency_differences(df_202123,"2021-23")

diffs <- rbind(df_201415_diff,df_202123_diff)

min_diff <- c(diffs %>% .$value %>% min %>% round() ) - 1
max_diff <- c(diffs%>% .$value %>% max %>% round() )

f <- ggplot(data = diffs ,aes(x = value)) + geom_histogram(fill='black',bins = 50) + facet_grid(study~variable)  + labs(x="Change in frequency relative to complete dataset (%)",y="Sequence types") + xlim(min_diff,max_diff)   + theme(panel.background = element_rect(fill = "white",colour = 'black'), panel.grid = element_blank(),                                                                                                                                             strip.background = element_rect(fill = "white",colour = "black",linewidth=1),                                                                                                                      panel.grid.major = element_blank(),                                                                                                                                                            panel.grid.minor = element_blank(),                                                                                                                                                          axis.line = element_line(colour = "black"),legend.position = "bottom") + scale_x_continuous(breaks = scales::pretty_breaks(8))
```

```{r,fig.width=7.375,fig.height=14.75}
AB <- cowplot::plot_grid(A,B,rel_widths = c(1,0.66),labels = "AUTO",ncol=2)
CD <- cowplot::plot_grid(C,D,NULL,rel_widths = c(1,1,.5),labels = c("C","D",""),ncol=3)
f_fig <- cowplot::plot_grid(f,NULL,rel_widths = c(1,0.25),labels = "F",ncol=2)
CDE <-  cowplot::plot_grid(CD,E,f_fig,ncol=1,rel_heights = c(1,2.5,1),labels = c("","E","")) 
figure <- cowplot::plot_grid(AB,CDE,ncol=1,labels = c("",""),rel_heights = c(0.2,1))
figure
```

```{r,fig.width=9,fig.height=4.5}  
ggsave(filename = "./figures/s_figure_X_repeated_samples.png",plot=figure,width = 14.75,height = 7.375,dpi=900,bg = 'white')
```