---
title: "Supplemental Figure 5: MIC correlation"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/')
```

# Environment
```{r}
library(tidyverse)
library(ggalluvial)
library(ComplexHeatmap)
library(cowplot)
library(tableone)
packages <- c("tidyverse",'ape','kableExtra','phytools','tableone','kableExtra','ggtree','phyloAMR','ggalluvial','colorRamp2') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()
```

# Load data
```{r}
df <- readRDS("~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/2025-09-18_master_kpn_first_isolate_dataset_curation/results/CA_clinical_CRKP_first_isolate_metadata_091825.RDS")  
  
df$study <- factor(df$study,levels = c("2014-15","2021-23"))
df_201415 <- df%>% subset(study == "2014-15")
df_202123<- df%>% subset(study == "2021-23")
```

# Complete case analysis
```{r}
paste0("Number of isolates: ", nrow(df_202123))
paste0("Number of individuals without metadata: ", nrow(df_202123 %>% subset(is.na(participant_id)))) 

MIC_variables <- c('MERO',"IMI",'blbli','MVB','IR','CZA',"CT","FDC","OMC","ERV","DLX","CST","PLZ","FOS") 
resistance_vars <- c(paste0(MIC_variables,"_dich_num"))

complete_case <- df_202123[df_202123 %>% select(resistance_vars) %>% is.na() %>% rowSums()  ==0  ,] 

paste0("Number of considered individuals with complete resistance datafor this analysis: ", nrow(complete_case ))
```


# Supplemental figure: Correlation matrix of MIC values
```{r,message=F,error=F,warning=F,fig.width=8.5,fig.height=6}
MIC_variables <- c('MERO',"IMI",'MVB','IR','CZA',"FDC","CT","OMC","ERV","DLX","CST","PLZ","FOS") 
MIC_correlation <-  cor(complete_case %>% select(paste0(MIC_variables,"_log_2")) , method="spearman",use='pairwise.complete.obs') %>% round(.,2)
 
drugs <-  rownames(MIC_correlation) %>% gsub("_log_2","",.)

corr_heatmap <- ComplexHeatmap::pheatmap(MIC_correlation %>% as.matrix,border_color = "black",name ="Spearman's rank correlation coefficient",legend=F,fontsize = 12,
    row_names_max_width = max_text_width(rownames(MIC_correlation), gp = gpar(fontsize = 14)),
    column_names_max_height = max_text_width(rownames(MIC_correlation), gp = gpar(fontsize = 14)),
    cluster_rows=T,cluster_cols = T,labels_row = drugs,labels_col=drugs,number_color = "black",breaks = c(-1,0,1),color=c("blue","white","red"),display_numbers = T)  

## Complex heatmap legend 
fig_legend <- Legend(at = c(-1, -0.5, 0, 0.5, 1),labels = c("-1.00", "-0.50", "0.00", "0.50", "1.00"),title = "Spearman's rank correlation coefficient",direction = "horizontal",col_fun = colorRamp2(breaks = c(-1,  0,  1),colors = c("blue","white","red")), title_gp = gpar(fontsize = 14),labels_gp=gpar(fontsize=12),legend_width = unit(10, "cm"), title_position = 'topcenter')
 
# Print heatmap
fig_heatmap_image <- grid.grabExpr(draw(corr_heatmap))
fig_legend_image <- grid.grabExpr(draw(fig_legend))

corrfig <- plot_grid(fig_heatmap_image,fig_legend_image,ncol=1,axis="l", align="hv",rel_heights = c(1,.15))
```

# Print & Save 
```{r,message=F,error=F,warning=F,fig.width=6.25,fig.height=5}
corrfig
```

```{r}
ggsave(plot = corrfig, filename = "./Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms/figures/s_figure_5_resistance_MIC_correlations.png", width = 6.25, height = 5.25, bg = "white",dpi=900)
```
