---
title: "Supplementary Figure 4: Carbapenemase resistance mutations"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms')
```

# Environment

```{r}
# Packages
packages <- c("tidyverse","gridExtra","kableExtra","tableone","cowplot")
lapply(packages,library,character.only=T)

# Functions
source("././lib/consistent_themes.R")
source("././lib/common_functions.R")

# Print environment
Sys.info()
sessionInfo()
```

# Load data

```{r}
df <- readRDS("./data/dataset/CA_LTACH_first_clinical_per_quarter_CRKP_genomes_merged_studies_metadata.RDS")

df_201415 <- df%>% subset(study == "2014-15")
df_202123 <- df%>% subset(study == "2021-23") 
``` 

# Load  carbapenemase content
```{r}
carbapenemase_content <- readRDS("./data/carbapenemase_content/carbapenemase_content_merged_studies.RDS")
df <- left_join(df,carbapenemase_content)
```

# Load omp matrix
```{r}
carb_omp <-  readRDS("./data/carbapenemase_content/carbapenem_resistance_genotype_content_merged_first_clinical_CRKP_isolate_per_quarter.RDS")
``` 

# Supplemental Figure:
```{r,fig.width=9.5,height=6.7857}  
df_carb_omp <- df %>% select(isolate_no,study,Species_ST_recode) %>% left_join(., carb_omp %>% mutate(isolate_no = rownames(.)))    %>% as.data.frame
rownames(df_carb_omp) <- df_carb_omp$isolate_no 
```

# Figure A. Count datag
```{r}
melted_row <- df_carb_omp %>% select(-isolate_no) %>% reshape2::melt(c("study","Species_ST_recode")) %>% subset(value == 1) 

isolates_1415 <- sum(grepl("PCMP",rownames(df_carb_omp)))
isolates_2123 <- sum(grepl("INT",rownames(df_carb_omp)))

# Calculate proportion of isolates in study but retain the major_ST coloring
melted_row_summary <- melted_row %>% group_by(study,Species_ST_recode,variable) %>% summarise(n=sum(value))
melted_row_summary$proportion <- ifelse(melted_row_summary$study =='2021-23',melted_row_summary$n/isolates_2123,melted_row_summary$n/isolates_1415)

melted_row_summary$percentage <- melted_row_summary$proportion * 100

# How to normalize data by count in study 
melted_row_summary$variable <- recode_genotypes(melted_row_summary$variable)
melted_row_summary$variable <- factor(melted_row_summary$variable,levels = melted_row_summary %>% group_by(variable) %>% summarise(tot=sum(n)) %>% arrange(-tot) %>% .$variable) 

melted_row_summary$variable_md <- sapply(melted_row_summary$variable,format_blaKPC_genotypes_md)  
melted_row_summary$variable_md <- factor(melted_row_summary$variable_md,levels = melted_row_summary %>% group_by(variable_md) %>% summarise(tot=sum(n)) %>% arrange(-tot) %>% .$variable_md)

A <- ggplot(data=melted_row_summary,aes(y=variable_md,fill=Species_ST_recode,x=percentage)) + geom_bar(stat='identity') + facet_wrap(~study)  + theme_bw_me + theme(axis.text.x = element_text(angle=0, hjust = 1, vjust = 0.5)) + ST_scale_2_row + xlab("Percentage of isolates") + ylab(NULL) + xlim(NA,100.1) +  
  geom_text(
  data = melted_row_summary %>% ungroup %>% select(-Species_ST_recode) %>% group_by(study,variable_md) %>% summarise(sumar= sum(percentage),count=sum(n)),
  inherit.aes = F,  
  aes(
    label = count,
    x = ifelse(sumar >100,sumar+5,ifelse(sumar >10,sumar+3.5,sumar+2.5)) ,
    y= variable_md
  ),
  size = 2.5,
) + scale_x_continuous(breaks = c(0,20,40,60,80,100),labels = c('0','20','40','60','80','100'),limits = c(0,100.1)) + ggtitle("All isolates")  + theme(legend.title.position = 'top',axis.text.y = element_markdown())

A
```

# Figure B. Non-carbapenemase isolates
```{r}
non_carbapenemase_isolates <- df %>% subset(carbapenemase=="No carbapenemase") %>% .$isolate_no
non_carbapenemase_isolates_1415 <- sum(grepl("PCMP",non_carbapenemase_isolates))
non_carbapenemase_isolates_2123 <- sum(grepl("INT",non_carbapenemase_isolates))

melted_row_no_carb<- df_carb_omp %>% select(-isolate_no) %>% subset(rownames(.) %in% non_carbapenemase_isolates) %>% reshape2::melt(c("study","Species_ST_recode")) %>% subset(value == 1)  

melted_row_no_carb_summary <- melted_row_no_carb %>% group_by(study,Species_ST_recode,variable) %>% summarise(n=sum(value))
melted_row_no_carb_summary$proportion <- ifelse(melted_row_no_carb_summary$study =='2021-23',melted_row_no_carb_summary$n/non_carbapenemase_isolates_2123,melted_row_no_carb_summary$n/non_carbapenemase_isolates_1415)
melted_row_no_carb_summary$percentage <- melted_row_no_carb_summary$proportion*100

# How to normalize data by count in study 
melted_row_no_carb_summary$variable <- recode_genotypes(melted_row_no_carb_summary$variable)
melted_row_no_carb_summary$variable <- factor(melted_row_no_carb_summary$variable,levels = melted_row_no_carb_summary %>% group_by(variable) %>% summarise(tot=sum(n)) %>% arrange(-tot) %>% .$variable)

melted_row_no_carb_summary$variable_md <- sapply(melted_row_no_carb_summary$variable,format_blaKPC_genotypes_md)  
melted_row_no_carb_summary$variable_md <- factor(melted_row_no_carb_summary$variable_md,levels = melted_row_no_carb_summary %>% group_by(variable_md) %>% summarise(tot=sum(n)) %>% arrange(-tot) %>% .$variable_md)

B <- ggplot(data=melted_row_no_carb_summary,aes(y=variable_md,fill=Species_ST_recode,x=percentage)) + geom_bar(stat='identity') + facet_wrap(~study)  + theme_bw_me + theme(axis.text.x = element_text(angle=0, hjust = 1, vjust = 0.5)) + ST_scale_2_row + xlab("Percentage of isolates") + ylab(NULL) + xlim(NA,100.1) +  
  geom_text(
  data = melted_row_no_carb_summary %>% ungroup %>% select(-Species_ST_recode) %>% group_by(study,variable_md) %>% summarise(sumar= sum(percentage),count=sum(n)),
  inherit.aes = F,  
  aes(
    label = count,
    x = ifelse(sumar >100,sumar+5,ifelse(sumar >10,sumar+3.5,sumar+2.5)),
    y= variable_md
  ),
  size = 2.5,
) + scale_x_continuous(breaks = c(0,20,40,60,80,100),labels = c('0','20','40','60','80','100'),limits = c(0,100.1)) + ggtitle("Non-carbapenemase-producing isolates") + theme(legend.title.position = 'top',axis.text.y = element_markdown())
B
```

# Create figure
```{r,fig.width=7.833333,fig.height=11.75}
legends <- cowplot::get_legend(A + theme(legend.title = element_text(size=10),
                                         legend.text = element_text(size=8),
                                         legend.key.size = unit(0.5,"cm")))
AB <- cowplot::plot_grid(A + theme(legend.position = 'none'),B+ theme(legend.position = 'none'),ncol=1,labels = c("A","B"),rel_heights = c(1,0.75))
figure <- cowplot::plot_grid(AB,legends,rel_heights = c(1,0.06667),ncol=1)

figure
```

```{r}
ggsave(filename = "./figures/s_figure_4_carbapenem_resistance_associated_genotypes_count.png",plot=figure,width = 7.833333,height = 11.75,dpi=900,bg = 'white')
```
