---
title: "phylogeographic_analyses"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms/')
```

# Environment

```{r environment, echo=F, message=FALSE, include=F, results=F}
#Packages
packages <- c("tidyverse") 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()
```


# Sample assembly list
```{r}
public_dataset <- readRDS("~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms/data/public_genomes/NCBI_metadata/NCBI_Pathogens_Kpn_metadata_isolates_w_spatiotemporal_data_121025.RDS")
public_dataset$assembly_name <- public_dataset$Assembly
paste0("Public genomes with isolate and spatiotemporal data: ",nrow(public_dataset))
kleborate_genome_list <- readr::read_lines("~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms/data/public_genomes/kleborate/partitions/NCBI_pathogens_genome_assembly_list.txt")
kleborate_genome_name <- str_split(kleborate_genome_list,pattern = '/',simplify = T) %>% .[,15]
paste0("Public genomes tested for Kleborate: ",length(kleborate_genome_list))
kleborate <- read_delim("~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms/data/public_genomes/kleborate/results/NCBI_pathogens_Kpn_kleborate.txt")
kleborate$assembly_name <- str_split(kleborate$strain,pattern = '_',simplify = T)   %>% .[,c(1,2)] %>% apply(.,1,paste0,collapse='_')
paste0("Public genomes with Kleborate Kpn species complex entry: ",nrow(kleborate))
paste0("Public genomes without Kleborate Kpn species complex entry: ",length(kleborate_genome_list) - nrow(kleborate))
public_dataset <- left_join(public_dataset,kleborate)
```

# Load QCD data
```{r}
qcd <- read_csv("~/Desktop/gl_nfs/Project_INTEGRATE/Public_datasets/2025-12-15_all_Kleb_NCBI_Pathogen/illumina/master_qc_summary_assembly.csv")
qcd$Assembly <- qcd$Sample
qcd <- qcd %>% rename('mlst_ST'= 'ST' ,
                      "pubQCD_N50"="N50")
public_dataset <- left_join(public_dataset,qcd)
public_dataset$isolate_no <- public_dataset$Assembly 
public_dataset$participant_id <- public_dataset$Assembly
```

# Load integrate data
```{r}
df <- readRDS("~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms/data/dataset/CA_LTACH_first_clinical_per_quarter_CRKP_genomes_merged_studies_metadata.RDS")
df_kleborate <- readRDS("~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms/data/kleborate/kleborate_kpsc_both_studies.RDS") 
df <- left_join(df,df_kleborate )
df$country <- "United States"
df$california <- TRUE
df$continent <- "Americas"
df$collection_date <- df$date
df$collection_year <- df$year
```

# Merge dataset
```{r}
voi <- c('isolate_no','participant_id','ST','collection_date','collection_year','continent','country','california')
combined_phylogeographic_df <- bind_rows(public_dataset %>% select(any_of(voi)),df %>% select(any_of(voi))) %>% as.data.frame
```

# Trees
```{r}
library(ape)
library(ggtree)
tr_ST14 <- read.tree("./data/phylogeny/phylogeographic/ST14/cognac_nj.tre") %>% drop.tip("INT_CRE_1243") %>% phytools::midpoint_root()
tr_ST17 <- read.tree("./data/phylogeny/phylogeographic/ST17/cognac_nj.tre") %>% drop.tip("INT_CRE_1243") %>% phytools::midpoint_root()
tr_ST307 <- read.tree("./data/phylogeny/phylogeographic/ST307/cognac_nj.tre") %>% drop.tip("INT_CRE_1243") %>% phytools::midpoint_root()
tr_ST258 <- read.tree("./data/phylogeny/phylogeographic/ST258/cognac_nj.tre") %>% drop.tip("INT_CRE_1243") %>% phytools::midpoint_root() 
```

```{r}
rownames(combined_phylogeographic_df) <- combined_phylogeographic_df$isolate_no
combined_phylogeographic_df$collection_decade <- floor(combined_phylogeographic_df$collection_year/10)*10
combined_phylogeographic_df$collection_year_fct <- as.factor(combined_phylogeographic_df$collection_year)
combined_phylogeographic_df$type <- ifelse(grepl("PCMP_H",combined_phylogeographic_df$isolate_no),"2014-15 CA LTACH",
                                           ifelse(grepl("INT_CRE_",combined_phylogeographic_df$isolate_no),"2021-23 CA LTACH","Public genomes"))
combined_phylogeographic_df$california_bin <- ifelse(combined_phylogeographic_df$california==T,1,0)

total_colors <- 10
all_colors <- hues::iwanthue(total_colors,plot = T)

decade_scale <- scale_fill_manual(breaks = c("1980","1990","2000","2010","2020"),values = all_colors[c(1,2,4,5,8)],name = "Decade",guide = guide_legend(nrow=3,order=1),drop=FALSE) 

continent_scale <- scale_fill_manual(breaks = c("Africa","Americas","Asia","Europe","Oceania"),values = all_colors[c(3,7,6,9,10)],name = "Continent",guide = guide_legend(nrow=3,order=2),drop=FALSE)

california_scale <- scale_fill_manual(breaks = c(TRUE,FALSE),values = c("black","white"),labels = c("California","Other"),name = "California",guide = guide_legend(nrow=3,order=3),drop=FALSE)

study_scale <- scale_fill_manual(breaks = c("2014-15 CA LTACH","2021-23 CA LTACH","Public genomes"),values = c("blue","red","darkgray"),name = "Type",guide = guide_legend(nrow=3,order=4),drop=FALSE)

study_scale_color <- scale_color_manual(breaks = c("2014-15 CA LTACH","2021-23 CA LTACH","Public genomes"),values = c("blue","red","darkgray"),name = "Type",guide = guide_legend(nrow=3,order=4),drop=FALSE)

combined_phylogeographic_df_top_STs <-  combined_phylogeographic_df %>% subset(ST %in% c("ST14","ST17",'ST258','ST307'))
combined_phylogeographic_df_top_STs$collection_decade <- factor(combined_phylogeographic_df_top_STs$collection_decade,levels = c("1980",'1990','2000','2010','2020'))
combined_phylogeographic_df_top_STs$continent <- factor(combined_phylogeographic_df_top_STs$continent,levels = c("Africa","Americas","Asia","Europe","Oceania"))
combined_phylogeographic_df_top_STs$california <- factor(combined_phylogeographic_df_top_STs$california,levels = c(TRUE,FALSE))
combined_phylogeographic_df_top_STs$type <- factor(combined_phylogeographic_df_top_STs$type,levels = c("2014-15 CA LTACH","2021-23 CA LTACH","Public genomes"))

CA_tips <- combined_phylogeographic_df_top_STs %>% subset(california==T) %>% .$isolate_no
 
```

## ST258
```{r} 

tr_data <- as_tibble(tr_ST258) %>%
  left_join(.,combined_phylogeographic_df_top_STs %>% subset(ST=="ST258"), by = c("label" = "isolate_no"))

p0 <- gheatmap(ggtree(tr_ST258) %<+% tr_data +
    geom_tippoint(aes(subset = california == T, color = type), size = 0.5) +study_scale_color  , combined_phylogeographic_df_top_STs %>% select(collection_decade) %>% `colnames<-`("Decade") ,color=NULL,width=0.1,colnames_position = 'top',colnames_angle = 90,colnames_offset_y = 25, hjust=0)+ decade_scale + ylim(NA,6500)
p0.1 <- p0+ggnewscale::new_scale_fill()
A <- gheatmap(p0.1, combined_phylogeographic_df_top_STs %>% select(continent)  %>% `colnames<-`("Continent") ,color=NULL,width=0.1,offset=0.0001,colnames_position = 'top',colnames_angle = 90,colnames_offset_y = 25,hjust=0) + continent_scale + ylim(NA,7250)
#p1.1 <- p1+ggnewscale::new_scale_fill()
#p2 <- gheatmap(p1.1, combined_phylogeographic_df_top_STs %>% select(california)  %>% `colnames<-`("California"),color=NULL,width=0.1,offset=0.0002,colnames_position = 'top',colnames_angle = 90,colnames_offset_y = 25,hjust=0)  + california_scale + ylim(NA,6500)
#p2.1 <- p2+ggnewscale::new_scale_fill()
#A <- gheatmap(p2.1, combined_phylogeographic_df_top_STs %>% select(type) %>%  `colnames<-`("Study") ,color=NULL,width=0.1,offset=0.0003,colnames_position = 'top',colnames_angle = 90,colnames_offset_y = 25,hjust=0)  + study_scale + ylim(NA,7250)
#A + ggtitle("ST258") + ylim(NA,7250) +
  
```

## ST14
```{r}
tr_data <- as_tibble(tr_ST14) %>%
  left_join(.,combined_phylogeographic_df_top_STs %>% subset(ST=="ST14"), by = c("label" = "isolate_no"))

p0 <- gheatmap(ggtree(tr_ST14)  %<+% tr_data +
    geom_tippoint(aes(subset = california == T, color = type), size = 1.25) +study_scale_color, combined_phylogeographic_df %>% select(collection_decade) %>% mutate_all(as.factor) %>% `colnames<-`("Decade") ,color=NULL,width=0.1,colnames_position = 'top',colnames_angle = 90,colnames_offset_y = 10, hjust=0) + hues::scale_fill_iwanthue() + decade_scale + ylim(NA,1780)
p0.1 <- p0+ggnewscale::new_scale_fill()
B <- gheatmap(p0.1, combined_phylogeographic_df %>% select(continent) %>% mutate_all(as.factor) %>% `colnames<-`("Continent"),color=NULL,width=0.1,offset=0.0002,colnames_position = 'top',colnames_angle = 90,colnames_offset_y = 10, hjust=0) + hues::scale_fill_iwanthue() + continent_scale + ylim(NA,2000)
#p1.1 <- p1+ggnewscale::new_scale_fill()


#p2 <- gheatmap(p1.1, combined_phylogeographic_df %>% select(california) %>% mutate_all(as.factor) %>% `colnames<-`("California"),color=NULL,width=0.1,offset=0.0004,colnames_position = 'top',colnames_angle = 90,colnames_offset_y = 10, hjust=0) + hues::scale_fill_iwanthue() + california_scale + ylim(NA,1780)
#p2.1 <- p2+ggnewscale::new_scale_fill()
#B <- gheatmap(p2.1, combined_phylogeographic_df %>% select(type) %>% mutate_all(as.factor) %>% `colnames<-`("Study"),color=NULL,width=0.1,offset=0.0006,colnames_position = 'top',colnames_angle = 90,colnames_offset_y = 10, hjust=0) + hues::scale_fill_iwanthue() + study_scale + ylim(NA,2000)
#B + ggtitle("ST14") + ylim(NA,2000)
```

# ST307
```{r}
tr_data <- as_tibble(tr_ST307) %>%
  left_join(.,combined_phylogeographic_df_top_STs %>% subset(ST=="ST307"), by = c("label" = "isolate_no"))

rownames(combined_phylogeographic_df) <- combined_phylogeographic_df$isolate_no
p0 <- gheatmap(ggtree(tr_ST307) %<+% tr_data +
    geom_tippoint(aes(subset = california == T, color = type), size = 1.25) +study_scale_color , combined_phylogeographic_df %>% select(collection_decade) %>% mutate_all(as.factor) %>% `colnames<-`('Decade') ,color=NULL,width=0.1,colnames_position = 'top',colnames_angle = 90,colnames_offset_y = 10, hjust=0) + hues::scale_fill_iwanthue() + decade_scale + ylim(NA,4500)
p0.1 <- p0+ggnewscale::new_scale_fill()
C <- gheatmap(p0.1, combined_phylogeographic_df %>% select(continent) %>% mutate_all(as.factor)%>% `colnames<-`("Continent") ,color=NULL,width=0.1,offset=0.000075,colnames_position = 'top',colnames_angle = 90,colnames_offset_y = 10, hjust=0) + hues::scale_fill_iwanthue() + continent_scale + ylim(NA,5000)
#p1.1 <- p1+ggnewscale::new_scale_fill()
#p2 <- gheatmap(p1.1, combined_phylogeographic_df %>% select(california) %>% mutate_all(as.factor)%>% `colnames<-`("California") ,color=NULL,width=0.1,offset=0.00015,colnames_position = 'top',colnames_angle = 90,colnames_offset_y = 10, hjust=0) + hues::scale_fill_iwanthue() + california_scale + ylim(NA,4500)
#p2.1 <- p2+ggnewscale::new_scale_fill()
#C <- gheatmap(p2.1, combined_phylogeographic_df %>% select(type) %>% mutate_all(as.factor) %>% `colnames<-`("Study"),color=NULL,width=0.1,offset=0.000225,colnames_position = 'top',colnames_angle = 90,colnames_offset_y = 10, hjust=0) + hues::scale_fill_iwanthue() + study_scale + ylim(NA,5000)

#C + ggtitle("ST307")+ ylim(NA,5000)
```

## ST17
```{r} 
tr_data <- as_tibble(tr_ST17) %>%
  left_join(.,combined_phylogeographic_df_top_STs %>% subset(ST=="ST17"), by = c("label" = "isolate_no"))

rownames(combined_phylogeographic_df) <- combined_phylogeographic_df$isolate_no
p0 <- gheatmap(ggtree(tr_ST17) %<+% tr_data +
    geom_tippoint(aes(subset = california == T, color = type), size = 1.25) +study_scale_color , combined_phylogeographic_df %>% select(collection_decade) %>% mutate_all(as.factor) %>% `colnames<-`('Decade') ,color=NULL,width=0.1,colnames_position = 'top',colnames_angle = 90,colnames_offset_y = 10, hjust=0) + hues::scale_fill_iwanthue() + decade_scale + ylim(NA,1600)
p0.1 <- p0+ggnewscale::new_scale_fill()
D <- gheatmap(p0.1, combined_phylogeographic_df %>% select(continent) %>% mutate_all(as.factor) %>% `colnames<-`("Continent"),color=NULL,width=0.1,offset=0.000175,colnames_position = 'top',colnames_angle = 90,colnames_offset_y = 10, hjust=0) + hues::scale_fill_iwanthue() + continent_scale + ylim(NA,1800)
#p1.1 <- p1+ggnewscale::new_scale_fill()
#p2 <- gheatmap(p1.1, combined_phylogeographic_df %>% select(california) %>% mutate_all(as.factor)%>% `colnames<-`("California") ,color=NULL,width=0.1,offset=0.00035,colnames_position = 'top',colnames_angle = 90,colnames_offset_y = 10, hjust=0) + hues::scale_fill_iwanthue() + california_scale + ylim(NA,1600)
#p2.1 <- p2+ggnewscale::new_scale_fill()
#D <- gheatmap(p2.1, combined_phylogeographic_df %>% select(type) %>% mutate_all(as.factor) %>% `colnames<-`("Study"),color=NULL,width=0.1,offset=0.000525,colnames_position = 'top',colnames_angle = 90,colnames_offset_y = 10, hjust=0) + hues::scale_fill_iwanthue() + study_scale + ylim(NA,1800)

#D + ggtitle("ST17")
```

# Create plots to grab legend! 
```{r}
decade <- ggplot(data=combined_phylogeographic_df_top_STs,aes(x=collection_decade,fill=collection_decade)) + geom_bar(stat='count') + decade_scale
continent <- ggplot(data=combined_phylogeographic_df_top_STs,aes(x=continent,fill=continent)) + geom_bar(stat='count') + continent_scale 
study <- ggplot(data=combined_phylogeographic_df_top_STs,aes(x=type,fill=type)) + geom_bar(stat='count') + study_scale

decade_legend <- cowplot::get_legend(decade) %>% cowplot::plot_grid()
continent_legend <- cowplot::get_legend(continent) %>% cowplot::plot_grid() 
study_legend <- cowplot::get_legend(study) %>% cowplot::plot_grid()

legends <- cowplot::plot_grid(decade_legend,continent_legend,study_legend,ncol=3)
```
 
# Cowplot figure
```{r,fig.width=10,fig.height=10}
main <- cowplot::plot_grid(A + theme(legend.position = 'none'),B+ theme(legend.position = 'none'),C+ theme(legend.position = 'none'),D+ theme(legend.position = 'none'),ncol=2,labels = c("A. ST258","B. ST14","C. ST307","D. ST14"))
figure <- cowplot::plot_grid(main,legends,ncol=1,rel_heights = c(1,0.1))
figure

ggsave(filename = "./figures/s_figure_1_phylogeographic.png",plot = figure,dpi=900,bg='white',height=10,width=10)
```

# Ancestral state reconstruction (will perform later)
```{r} 
# # ST258
# ST258_CA_asr <- phyloAMR::asr(df=combined_phylogeographic_df %>% subset(isolate_no %in% tr_ST258$tip.label),tr=tr_ST258,'isolate_no',trait = "california_bin",model = 'MF')
# 
# ST258_CA_asr_cluster <- phyloAMR::asr_cluster_detection(df = combined_phylogeographic_df %>% subset(isolate_no %in% tr_ST258$tip.label),tr=tr_ST258,tip_name_variable = 'isolate_no',patient_id = 'participant_id',parent_child_df = ST258_CA_asr$parent_child_df,node_states = 'joint',confidence = NULL,simplify_faux_clusters = T,simplify_revertant = T,collapse_cluster = T)
# 
# ST258_CA_asr$parent_child_df %>% .$gain %>% table
# ST258_CA_asr_cluster$singleton <- ST258_CA_asr_cluster$asr_cluster  =='singleton'
# ST258_CA_asr_cluster$asr_cluster %>% table
# 
# #ST14
# ST14_CA_asr <- phyloAMR::asr(df=combined_phylogeographic_df %>% subset(isolate_no %in% tr_ST14$tip.label),tr=tr_ST14,'isolate_no',trait = "california_bin")
# ST14_CA_asr_cluster <- phyloAMR::asr_cluster_detection(df = combined_phylogeographic_df %>% subset(isolate_no %in% tr_ST14$tip.label),tr=tr_ST14,tip_name_variable = 'isolate_no',patient_id = 'participant_id',parent_child_df = ST14_CA_asr$parent_child_df,node_states = 'joint',confidence = NULL,simplify_faux_clusters = T,simplify_revertant = T,collapse_cluster = T)
# 
# ST14_CA_asr$parent_child_df %>% .$gain %>% table
# ST14_CA_asr_cluster$asr_cluster %>% table
# 
# # ST17
# ST17_CA_asr <- phyloAMR::asr(df=combined_phylogeographic_df %>% subset(isolate_no %in% tr_ST17$tip.label),tr=tr_ST17,'isolate_no',trait = "california_bin")
# 
# ST17_CA_asr_cluster <- phyloAMR::asr_cluster_detection(df = combined_phylogeographic_df %>% subset(isolate_no %in% tr_ST17$tip.label),tr=tr_ST17,tip_name_variable = 'isolate_no',patient_id = 'participant_id',parent_child_df = ST17_CA_asr$parent_child_df,node_states = 'joint',confidence = NULL,simplify_faux_clusters = T,simplify_revertant = T,collapse_cluster = T)
# 
# ST17_CA_asr$parent_child_df %>% .$gain %>% table
# ST17_CA_asr_cluster$asr_cluster %>% table
# 
# # ST307
# ST307_CA_asr <- phyloAMR::asr(df=combined_phylogeographic_df %>% subset(isolate_no %in% tr_ST307$tip.label),tr=tr_ST307,'isolate_no',trait = "california_bin",model = 'MF')
# 
# ST307_CA_asr_cluster <- phyloAMR::asr_cluster_detection(df = combined_phylogeographic_df %>% subset(isolate_no %in% tr_ST307$tip.label),tr=tr_ST307,tip_name_variable = 'isolate_no',patient_id = 'participant_id',parent_child_df = ST307_CA_asr$parent_child_df,node_states = 'joint',confidence = NULL,simplify_faux_clusters = T,simplify_revertant = T,collapse_cluster = T)
# 
# ST307_CA_asr$parent_child_df %>% .$gain %>% table
# ST307_CA_asr_cluster$singleton <- ST307_CA_asr_cluster$asr_cluster  =='singleton'
# ST307_CA_asr_cluster$asr_cluster %>% table
```



