---
title: "Supplemental Figure 11: Resistance by taxonomy in 2014-15 study"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---
 

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms')
```

# Environment

```{r}
# Packages
packages <- c("tidyverse","gridExtra","kableExtra","tableone","gontjesr","cowplot","ComplexHeatmap",'ggalluvial')
lapply(packages,library,character.only=T)

# Functions
source("./lib/consistent_themes.R")

# Print environment
Sys.info()
sessionInfo()
```

# Load data
```{r} 
df <- readRDS("./data/dataset/CA_LTACH_first_clinical_per_quarter_CRKP_genomes_merged_studies_metadata.RDS")   
df_201415 <- df%>% subset(study == "2014-15")
df_202123<- df%>% subset(study == "2021-23") 

MIC_variables <- c('MERO',"IMI",'blbli','MVB','IR','CZA',"CST","PLZ","FOS") 
resistance_vars <- paste0(MIC_variables,"_dich_num")  
```
  

# Resistance by ST in 2014-15 study
```{r} 
df_201415_melt <-  reshape2::melt(df_201415 %>% select(isolate_no,ST,any_of(resistance_vars)), id.var=c('isolate_no',"ST"))  %>% group_by(ST,variable) %>%  summarise(count = sum(as.numeric(value),na.rm = T),prop = count / n())  

# Count of species
species_count <-  reshape2::melt(df_201415 %>% select(isolate_no,ST), id.var=c('isolate_no',"ST"))  %>% group_by(ST) %>%  summarise(count = n()) 

# Convert to wide format where rows are species and columns are resistance variables
df_201415_melt$count <- as.numeric(df_201415_melt$count)
df_201415_melt$prop <- as.numeric(df_201415_melt$prop)
df_201415_wide <- df_201415_melt %>% select(-count) %>% pivot_wider(names_from = variable, values_from = prop, values_fill = 0) 
df_201415_wide <- df_201415_wide[match(species_count$ST,df_201415_wide$ST),]
df_201415_wide$number_of_isolates <- sapply(df_201415_wide$ST,FUN=function(x){
  subset(species_count,ST == x) %>% .[["count"]]
})
 
df_201415_wide <- ungroup(df_201415_wide)
df_201415_wide <- as.data.frame(df_201415_wide)
rownames(df_201415_wide) <- paste0(df_201415_wide$ST, " (n=",df_201415_wide$number_of_isolates,")")

# Proportion data
df_201415_count <- df_201415_melt %>% select(-prop) %>% pivot_wider(names_from = variable, values_from = count, values_fill = 0) 
df_201415_count <- df_201415_count[match(species_count$ST,df_201415_count$ST),] %>% ungroup %>% select(-ST)
colnames(df_201415_wide) <-  recode(colnames(df_201415_wide),
                         "CZA_dich_num"='Ceftazidime-avibactam',
                         "CST_dich_num"='Colistin', 
                         'MERO_dich_num'='Meropenem',
                         'IMI_dich_num'='Imipenem',
                         "blbli_dich_num"='BL/BLI agents',
                         "MVB_dich_num"='Meropenem-vaborbactam',
                         "IR_dich_num"='Imipenem-relebactam',
                         "PLZ_dich_num"='Plazomicin',
                         "TMP_SMX_dich_num"='Trimethoprim-Sulfamethoxazole',
                         "OMC_dich_num" = "Omadacycline",
                         "DLX_dich_num" = "Delafloxacin",
                         "ERV_dich_num" = "Eravacycline",
                         "FOS_dich_num" = "Fosfomycin",
                         "CT_dich_num" = "Ceftolozane-tazobactam",
                         "FDC_dich_num"="Cefiderocol")

df_201415_wide_mat <- df_201415_wide %>% select(-ST, -number_of_isolates)   

colnames(df_201415_wide_mat) <- paste0(colnames(df_201415_wide_mat)," (n=",colSums(df_201415_count) ,")")
  
fig <- ComplexHeatmap::Heatmap(df_201415_wide_mat,
  name = "Resistance", 
  column_title = "", 
  row_title = "",
  row_names_side = "left",
  column_names_side = "top",
  column_names_rot = 90,
  row_names_gp = gpar(fontsize = 8),
  column_names_gp = gpar(fontsize = 8),
  cluster_rows = T, cluster_columns = T,
  show_row_dend = FALSE, show_column_dend = FALSE,
  show_row_names = TRUE, show_column_names = TRUE,
  row_title_gp = gpar(fontsize = 6),
  column_title_gp = gpar(fontsize = 6),
  cell_fun = function(j, i, x, y, width, height, fill) {
    val <-  df_201415_count[i, j]
    if(val >0){
    grid.text(sprintf("%.0f", df_201415_count[i, j]), x, y, gp = gpar(fontsize = 8))
    }
  },
  col = c("white", "red"),
  column_gap = unit(0, "mm"),
  row_gap = unit(0, "mm"),
  show_heatmap_legend = FALSE,width = unit(7.5, "cm")
)
``` 

```{r,fig.width=4,fig.height=4}
fig
fig_ht <- grid.grabExpr(draw(fig))
```

```{r}
ggsave(filename = "./figures/s_figure_11_resistance_by_taxonomy_201415.png",plot=fig_ht,width = 4,height = 4,dpi=900,bg = 'white')
```
