---
title: "Supplementary Figure 14: Resistance by taxonomy"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---
 
```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms')
```

# Environment

```{r}
# Packages
packages <- c("tidyverse","gridExtra","kableExtra","tableone","cowplot","ComplexHeatmap",'colorRamp2')
lapply(packages,library,character.only=T)

# Functions
source("./lib/consistent_themes.R")
source("./lib/common_functions.R")

# Print environment
Sys.info()
sessionInfo()
```

# Load data
```{r} 
df <- readRDS("./data/dataset/CA_LTACH_first_clinical_per_quarter_CRKP_genomes_merged_studies_metadata.RDS")    
df_201415 <- df%>% subset(study == "2014-15")
df_202123<- df%>% subset(study == "2021-23") 
```

# Generate order
```{r}
ST_order <- get_ranking(df,"ST",NULL) 
```

# Get figure
```{r}
get_figure <- function(df,ST_order,resistance_vars,title){
  
# Melt dataset
df_melt <-  reshape2::melt(df %>% select(isolate_no,ST,any_of(resistance_vars)), id.var=c('isolate_no',"ST"))  %>% group_by(ST,variable) %>%  summarise(count = sum(as.numeric(value),na.rm = T),prop = count / n(),perc = prop * 100)  
df_melt$count <- as.numeric(df_melt$count)
df_melt$prop <- as.numeric(df_melt$prop)
df_melt$perc <- as.numeric(df_melt$perc)

# ST count
ST_count <-  reshape2::melt(df %>% select(isolate_no,ST), id.var=c('isolate_no',"ST"))  %>% group_by(ST) %>%  summarise(count = n()) 

# Convert to wide format where rows are species and columns are resistance variables
df_wide_prop <- df_melt %>% select(-count,-perc) %>% pivot_wider(names_from = variable, values_from = prop, values_fill = 0) 
idx <- match(ST_order, df_wide_prop$ST)
df_wide_prop <- df_wide_prop[idx[!is.na(idx)], ]
df_wide_prop$number_of_isolates <- sapply(df_wide_prop$ST,FUN=function(x){
  subset(ST_count,ST == x) %>% .[["count"]]
})
 
df_wide_prop <- as.data.frame(ungroup(df_wide_prop)) 
rownames(df_wide_prop) <- paste0(df_wide_prop$ST, " (n=",df_wide_prop$number_of_isolates,")")
colnames(df_wide_prop) <-  recode_resistance_variables(colnames(df_wide_prop)) 

# Count data
df_count <- df_melt %>% select(-prop,-perc) %>% pivot_wider(names_from = variable, values_from = count, values_fill = 0)  
df_count <- df_count[idx[!is.na(idx)], ]  %>% ungroup %>% select(-ST)
colnames(df_count) <-  recode_resistance_variables(colnames(df_count)) 

df_wide_mat <- df_wide_prop %>% select(-ST, -number_of_isolates)   

colnames(df_wide_mat) <- paste0(colnames(df_wide_mat)," (n=",colSums(df_count) ,")")
df_wide_mat <- as.matrix(df_wide_mat)  

fig <- ComplexHeatmap::Heatmap(df_wide_mat,
  name = "Resistance", 
  column_title = title, 
  row_title = "",
  row_names_side = "left",
  column_names_side = "top",
  column_names_rot = 90,
  row_names_gp = gpar(fontsize = 8),
  column_names_gp = gpar(fontsize = 8),
  cluster_rows = F, cluster_columns = F,
  show_row_dend = FALSE, show_column_dend = FALSE,
  show_row_names = TRUE, show_column_names = TRUE,
  row_title_gp = gpar(fontsize = 10),
  column_title_gp = gpar(fontsize = 10),
  cell_fun = function(j, i, x, y, width, height, fill) {
    val <-  df_count[i, j]
    if(val >0){
    grid.text(sprintf("%.0f", df_count[i, j]), x, y, gp = gpar(fontsize = 8))
    }
  },
  col = c("white", "red"),
  column_gap = unit(0, "mm"),
  row_gap = unit(0, "mm"),
  show_heatmap_legend = FALSE,
  height =   nrow(df_wide_mat)*unit(5, "mm"),
  width =   ncol(df_wide_mat)*unit(5, "mm")
    
)
return(fig)
}

A <- get_figure(df_201415,ST_order,resistance_vars = rev(resistance_vars %>% subset(!. %in% c("FDC_dich_num","OMC_dich_num","ERV_dich_num","DLX_dich_num","CT_dich_num"  ))),title = '2014-15')
B <- get_figure(df_202123,ST_order,resistance_vars = rev(resistance_vars),title = '2021-23')

fig_legend <- Legend(at = c(0, 0.2,0.4,0.6,0.8, 1),labels = c("0%", "25%", "40%", "60%", "80%","100%"),title = "Percentage of isolates",direction = "horizontal",col_fun = colorRamp2(breaks = c(0, 1),colors = c("white","red")), title_gp = gpar(fontsize = 10),labels_gp=gpar(fontsize=8),legend_width = unit(4.5, "cm"), title_position = 'topcenter')
  
fig_legend_image <- grid.grabExpr(draw(fig_legend),width = 2.16) %>% cowplot::plot_grid(.,align = 'hv')
```

```{r,fig.width=7.2,fig.height=9.25}
# Grab graphical expressions
p1 = grid.grabExpr(draw(A,heatmap_legend_list=fig_legend,heatmap_legend_side = "bottom",align_heatmap_legend = "heatmap_center"))
p2 = grid.grabExpr(draw(B))

A_fig <- cowplot::plot_grid(p1,NULL,rel_heights = c(1,1.245),ncol=1,align = 'v')
# Combine different dimensions
figure <- plot_grid(A_fig, p2, ncol = 2,rel_widths = c(0.6,1),labels = c("A","B"),hjust = -0.1)

figure

ggsave(filename = "./figures/s_figure_14_resistance_by_taxonomy.png",figure,width=7.2,height=9.25,units = 'in',dpi=900,bg='white')
``` 
