---
title: "Supplementary Figure 8: Carbapenemase plasmid replicon data"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = TRUE,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms')
```

# Environment

```{r}
# Packages
packages <- c("tidyverse","gridExtra","kableExtra","tableone","cowplot","ComplexHeatmap",'ggalluvial')
lapply(packages,library,character.only=T)

# Functions
source("./lib/consistent_themes.R")

# Print environment
Sys.info()
sessionInfo()
```

# Load data

```{r}
df <- readRDS("./data/dataset/CA_LTACH_first_clinical_per_quarter_CRKP_genomes_merged_studies_metadata.RDS")   
```

# Coordinate sequence type data

```{r}  
df$Species_ST_recode_no_species <- gsub("Klebsiella pneumoniae ","",df$Species_ST)
 
df_201415 <- df%>% subset(study == "2014-15")
df_202123<- df%>% subset(study == "2021-23")
```

# Load carbapenemase data
```{r}
carbapenemase_content <- readRDS("./data/carbapenemase_content/carbapenemase_content_merged_studies.RDS")
df <- left_join(df,carbapenemase_content)
```

# Load plasmid data
```{r} 
KPC_plasmid_matrix <- readRDS("./data/carbapenemase_content/carbapenemase_plasmid_matrix.RDS") %>% subset(rownames(.) %in% df$isolate_no)
df <- left_join(df,KPC_plasmid_matrix %>% mutate(isolate_no = rownames(.)))
mobtyper_mat <- readRDS("./data/mobsuite/mobtyper_merged_w_carbapenemase_data.RDS") %>% subset(isolate_no %in% df$isolate_no)
```

```{r}
mobtyper_merged <- readRDS("./data/mobsuite/mobtyper_merged_w_carbapenemase_data.RDS") %>% subset(isolate_no %in% df$isolate_no)
```

# Plasmid data

```{r} 
isolates_w_carbapenemase_plasmid <- df %>% subset(!carbapenemase_plasmid %in% c("No carbapenemase","Chromosome") & carbapenemase_plasmid_replicon_type != "")

isolates_w_carbapenemase_plasmid_and_replicon_assignment <- isolates_w_carbapenemase_plasmid %>% subset(carbapenemase_plasmid_replicon_type!= "Unresolved")
isolates_w_carbapenemase_plasmid_ct <- nrow(isolates_w_carbapenemase_plasmid)
isolates_w_carbapenemase_plasmid_and_replicon_assignment_ct <- nrow(isolates_w_carbapenemase_plasmid_and_replicon_assignment)
``` 

# Split
```{r}
carbapenemase_plasmid_dataset <- mobtyper_merged %>% subset(carbapenemase_plasmid==1)

get_presence_absence_matrix_sep_specific_split<- function(df,variable,separator){
  presences <- str_split(unlist(c(df %>% dplyr::select(paste0(variable)))),separator) %>% unlist(.)  %>% unique(.) %>% .[!. %in% "-"] %>% sort %>% subset(!. %in% c(NA,"")) 
  vector <- as.vector(tidyr::unite(df %>% dplyr::select(paste0(variable)),determinants,sep =separator)) %>% unlist() %>% as.vector
  results <- matrix(nrow = nrow(df),ncol=length(presences))  %>% `colnames<-`(presences)
for(i in presences){
  results[,paste0(i)] <-  results[,paste0(i)] <-as.vector(ifelse(unlist(lapply(str_split(as.matrix(df[,paste0(variable)]),separator), function(x) i %in% x))==TRUE,1,0))
}
  results <- as.data.frame(results)
  results$isolate_no = df$isolate_no
  results$carbapenemase_plasmid = df$primary_cluster_id
  results$carbapenemase = df$carbapenemase
     
  return(results)
}

plasmid_level_rep_data <- get_presence_absence_matrix_sep_specific_split(df = carbapenemase_plasmid_dataset, variable = 'rep_types',separator=',')
plasmid_level_rep_data <- left_join(plasmid_level_rep_data,df %>% select(isolate_no,Species_ST_recode,study))
```


```{r,fig.width=7.5,fig.height=7.5} 
variables_of_interest <- plasmid_level_rep_data %>% select(-isolate_no,-carbapenemase_plasmid,-Species_ST_recode,-study,-carbapenemase) %>% colnames()
```

```{r,fig.width=7.5,fig.height=7.5}  
study_colors <- setNames(object = study_comparison_scale_fill$palette(1),study_comparison_scale_fill$breaks)  
ST_colors <- setNames(object = ST_scale$palette(1),ST_scale$breaks)   %>% subset(names(.) %in% unique(plasmid_level_rep_data$Species_ST_recode))
plasmid_colors <- setNames(object = plasmid_fill_scale$palette(1),plasmid_fill_scale$breaks)   %>% subset(names(.) %in% unique(plasmid_level_rep_data$carbapenemase_plasmid))
carbapenemase_colors <- setNames(object = carbapenemase_scale$palette(1),carbapenemase_scale$breaks  %>% gsub("<i>bla</i><sub>","bla",.) %>% gsub("</sub>","",.) %>% trimws(.,"both"))   %>% subset(names(.) %in% unique(plasmid_level_rep_data$carbapenemase))

legend_common_features <- list(
  title_gp = gpar(fontsize = 9),
  labels_gp = gpar(fontsize = 9),
  grid_width = unit(0.25, "cm"),
  grid_height = unit(0.25, "cm")
)

rowannots <- rowAnnotation(
    Study = plasmid_level_rep_data$study,
    `Sequence type (ST)` = plasmid_level_rep_data$Species_ST_recode,
    `Plasmid cluster` = plasmid_level_rep_data$carbapenemase_plasmid,
    Carbapenemase = plasmid_level_rep_data$carbapenemase,

    col = list(
        Study =study_colors,
        `Sequence type (ST)` = ST_colors,
        Plasmid = plasmid_colors,
        Carbapenemase = carbapenemase_colors
    ),
      annotation_legend_param = list(   
    Study = c(legend_common_features,list(ncol=2)), 
    `Sequence type (ST)` =c(legend_common_features,list(at = ST_scale$breaks,ncol=2)),  
    `Plasmid cluster` =c(legend_common_features,list(at = plasmid_fill_scale$breaks,ncol=2)),  
    Carbapenemase =c(legend_common_features,list(at=carbapenemase_scale$breaks %>% gsub("<i>bla</i><sub>","bla",.) %>% gsub("</sub>","",.) %>% trimws(.,"both") ,ncol=1))),
    
  annotation_name_gp = gpar(fontsize=9)
)

heatmap_figure <- ComplexHeatmap::Heatmap(
    plasmid_level_rep_data %>% select(variables_of_interest), 
    name = "Replicon presence",  show_row_names = F,
                                              show_row_dend = T,
                                              show_column_dend = T,
                                              show_parent_dend_line = F,
    col=c("white","black"),
    row_split = plasmid_level_rep_data$Species_ST_recode,
    cluster_rows = TRUE,
    cluster_row_slices = TRUE,
    cluster_columns = TRUE, 
                                              gap = unit(0.2, "mm") ,
    right_annotation = rowannots,
    heatmap_legend_param = list( 
        labels = c("1" = "Present","0" = "Absent"),
        ncol=2,

        border = "black",
    labels_gp = gpar(fontsize = 9),
    title_gp = gpar(fontsize =9),  
    grid_width = unit(0.25,"cm"),
    grid_height = unit(0.25,"cm")
    ),
    row_names_gp = gpar(fontsize = 0),
  column_names_gp = gpar(fontsize = 9), 
  row_title = NULL, 
  cluster_column_slices = T
)

heatmap_figure  
```


```{r,fig.width=7.5,fig.height=7.5} 
fig_heatmap_image <- grid.grabExpr(draw(heatmap_figure))
figure <- cowplot::plot_grid(heatmap_figure) 
ggsave(filename = "./figures/s_figure_8_carbapeemase_plasmid_replicon_type_heatmap.png",plot=figure,width = 7.5,height = 7.5,dpi=900,bg = 'white')
``` 