---
title: "Supplemental Figure 4: Carbapenem resistance-associated genotype matrix"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms')
```

# Environment

```{r}
# Packages
packages <- c("tidyverse","gridExtra","kableExtra","tableone","gontjesr","cowplot","ComplexHeatmap",'ggalluvial')
lapply(packages,library,character.only=T)

# Functions
source("./lib/consistent_themes.R")

# Print environment
Sys.info()
sessionInfo()
```

# Load data

```{r}
df <- readRDS("./data/dataset/CA_LTACH_first_clinical_per_quarter_CRKP_genomes_merged_studies_metadata.RDS")   
   
df_201415 <- df%>% subset(study == "2014-15")
df_202123 <- df%>% subset(study == "2021-23") 
```

# Coordinate ST data

```{r} 
break_of_sts <-  c(sort(unique(df$Species_ST_recode %>% subset(.!="Singleton STs"))),"Singleton STs")
break_of_sts_renamed <- gsub("Klebsiella pneumoniae ","",break_of_sts)
       
ST_scale <- scale_fill_manual(breaks = break_of_sts,values = c(hues::iwanthue(n = length(unique(df$Species_ST_recode)) -1),"lightgray"),labels = break_of_sts_renamed,name = "Sequence type", guide = guide_legend(ncol=7, title.position = "top", label.position = "right"))

ST_palette <- ST_scale$palette(1) 
ST_palette <- c(ST_palette,"Other STs"='lightgray')
ST_major_scale <- scale_fill_manual(values = ST_palette,name = "Major sequence types (STs)")
```

# Load  carbapenemase content
```{r}
carbapenemase_content <- readRDS("./data/carbapenemase_content/carbapenemase_content_merged_studies.RDS")
df <- left_join(df,carbapenemase_content)
```

# Load omp matrix
```{r}
carb_omp <-  readRDS("./data/carbapenemase_content/carbapenem_resistance_genotype_content_merged_first_clinical_CRKP_isolate_per_quarter.RDS")
``` 

# Supplemental Figure:
```{r,fig.width=9.5,height=6.7857}  
df_carb_omp <- df %>% select(isolate_no,carbapenemase,study,major_STs) %>% left_join(., carb_omp %>% mutate(isolate_no = rownames(.)))    %>% as.data.frame
rownames(df_carb_omp) <- df_carb_omp$isolate_no 
```

# Get matrix 
  
```{r,fig.width=8.5,height=8.5}
# Carb
df_melt <- df  %>% select(Species_ST,carbapenemase)  %>%
  separate_rows(carbapenemase, sep = " & ") %>%  # split the genotypes
  count(Species_ST,carbapenemase, sort = TRUE)  %>%
    group_by(Species_ST) %>%
    mutate(prop = n / sum(n)) %>%
    ungroup()
 
# Scales 
genotypes <- c(table(df$carbapenemase %>% subset(.!="No carbapenemase")) %>% sort(decreasing = T) %>% names,"No carbapenemase")
genotype_colors <- setNames(c(hues::iwanthue(length(genotypes)-1,hmin = 5,cmin = 5,lmin = 5),"gray"), genotypes)
genotype_scale <- scale_fill_manual(breaks = genotypes,values = genotype_colors,name = "Carbapenemase", guide = guide_legend(ncol=4, title.position = "top", label.position = "right")) 
 
#ST
ST_palette <- ST_scale$palette(1) 
ST_palette <- c(ST_palette,"Other STs"='lightgray')

row_annots <- rowAnnotation(Study = df$study,`Major STs` = df$major_STs,
                            Carbapenemase = df$carbapenemase,
                            col = list(Study = c('2014-15'='blue','2021-23'='red'),Carbapenemase = genotype_colors ,`Major STs`=ST_palette %>% subset(names(.) %in% c(unique(df$major_STs)))), annotation_name_gp = gpar(fontsize = 8.5),annotation_legend_param = list( 
    title_gp = gpar(fontsize = 9),
    labels_gp = gpar(fontsize = 9),
    grid_width = unit(.25, "cm"),
    grid_height = unit(.25, "cm")
  ))

porin_bla_genotype <- ComplexHeatmap::Heatmap(df_carb_omp %>%  select(-carbapenemase,-study,-major_STs) %>% mutate_all(as.numeric) %>% select_if(colSums(.,na.rm = T)>0) %>% subset(is.na(rowSums(.))==F) %>% `colnames<-`(recode(colnames(.),"ompK35_rare_truncation"='Rare ompK35 truncation',"ompK36_rare_truncation"='Rare ompK36 truncation',"OmpK36GD" = "GD loop 3 insertion in ompK36","OmpK36TD" = "TD loop 3 insertion in ompK36","OmpK36_c25t" = "C25T mutation in ompK36","Rare_ompK35_insertion" = "Rare ompK356 insertion",'Rare_ompK36_insertion' = 'Rare ompK36 insertion', "ompK36_T136TDT" = 'ompK36 T136TDT', "ompK36_D135DGD" = "ompK36 D135DGD","ompK36_D135DD" ="ompK36 D135DD","blaSHV_C-112A" = 'blaSHV C112A') %>% gsub("Rare_","Rare ",.)) ,col=c("white","black"),show_row_names = F,show_row_dend = F,show_column_dend = F,name = "Genotype",gap = unit(0.4, "mm") ,right_annotation = row_annots,
  heatmap_legend_param = list(
    labels = c("1" = "Present","0" = "Absent"),
    labels_gp = gpar(fontsize = 9),
    title_gp = gpar(fontsize =9)
  ),row_names_gp = gpar(fontsize = 0),
    column_names_gp = gpar(fontsize = 9),row_split = df$major_STs,
  row_title = NULL,
  cluster_row_slices = T,
  cluster_column_slices = T
      ) 

ht_draw <- grid.grabExpr(draw((porin_bla_genotype)))
gghtmp <- cowplot::plot_grid(ht_draw)
gghtmp
```

# Save
  
```{r,fig.width=8.5,height=10.2}
ggsave(filename = "./figures/s_figure_4_carbapenem_resistance_associated_genotypes_matrix.png",plot=gghtmp,width = 8.5,height = 8.5,dpi=900,bg = 'white')
```
