---
title: "Supplemental Figure 2: Carbapenemase resistance mutations"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms')
```

# Environment

```{r}
# Packages
packages <- c("tidyverse","gridExtra","kableExtra","tableone","gontjesr","cowplot")
lapply(packages,library,character.only=T)

# Functions
source("././lib/consistent_themes.R")

# Print environment
Sys.info()
sessionInfo()
```

# Load data

```{r}
df <- readRDS("./data/dataset/CA_LTACH_first_clinical_per_quarter_CRKP_genomes_merged_studies_metadata.RDS")   
   
df_201415 <- df%>% subset(study == "2014-15")
df_202123 <- df%>% subset(study == "2021-23") 
```

# Coordinate ST data

```{r} 
break_of_sts <-  c(sort(unique(df$Species_ST_recode %>% subset(.!="Singleton STs"))),"Singleton STs")
break_of_sts_renamed <- gsub("Klebsiella pneumoniae ","",break_of_sts)
       
ST_scale <- scale_fill_manual(breaks = break_of_sts,values = c(hues::iwanthue(n = length(unique(df$Species_ST_recode)) -1),"lightgray"),labels = break_of_sts_renamed,name = "Sequence type", guide = guide_legend(ncol=7, title.position = "top", label.position = "right"))

ST_palette <- ST_scale$palette(1) 
ST_palette <- c(ST_palette,"Other STs"='lightgray')
ST_major_scale <- scale_fill_manual(values = ST_palette,name = "Major sequence types (STs)")
```

# Load  carbapenemase content
```{r}
carbapenemase_content <- readRDS("./data/carbapenemase_content/carbapenemase_content_merged_studies.RDS")
df <- left_join(df,carbapenemase_content)
```

# Load omp matrix
```{r}
carb_omp <-  readRDS("./data/carbapenemase_content/carbapenem_resistance_genotype_content_merged_first_clinical_CRKP_isolate_per_quarter.RDS")
``` 

# Supplemental Figure:
```{r,fig.width=9.5,height=6.7857}  
df_carb_omp <- df %>% select(isolate_no,study,major_STs) %>% left_join(., carb_omp %>% mutate(isolate_no = rownames(.)))    %>% as.data.frame
rownames(df_carb_omp) <- df_carb_omp$isolate_no 
```

# Figure A. Count datag
```{r}
melted_row <- df_carb_omp %>% select(-isolate_no) %>% reshape2::melt(c("study","major_STs")) %>% subset(value == 1) 

isolates_1415 <- sum(grepl("PCMP",rownames(df_carb_omp)))
isolates_2123 <- sum(grepl("INT",rownames(df_carb_omp)))

# Calculate proportion of isolates in study but retain the major_ST coloring
melted_row_summary <- melted_row %>% group_by(study,major_STs,variable) %>% summarise(n=sum(value))
melted_row_summary$proportion <- ifelse(melted_row_summary$study =='2021-23',melted_row_summary$n/isolates_2123,melted_row_summary$n/isolates_1415)

# How to normalize data by count in study 
melted_row_summary$variable <- recode(melted_row_summary$variable,"ompK35_rare_truncation"='Rare ompK35 truncation',"ompK36_rare_truncation"='Rare ompK36 truncation',"OmpK36GD" = "GD loop 3 insertion in ompK36","OmpK36TD" = "TD loop 3 insertion in ompK36","OmpK36_c25t" = "C25T mutation in OmpK36") %>% gsub("Rare_","Rare ",.)
melted_row_summary$variable <- factor(melted_row_summary$variable,levels = melted_row_summary %>% group_by(variable) %>% summarise(tot=sum(n)) %>% arrange(-tot) %>% .$variable)

A <- ggplot(data=melted_row_summary,aes(y=variable,fill=major_STs,x=proportion)) + geom_bar(stat='identity') + facet_wrap(~study)  + theme_bw_me + theme(axis.text.x = element_text(angle=0, hjust = 1, vjust = 0.5)) +ST_major_scale + xlab("Percentage") + ylab(NULL) + xlim(NA,1.01) +  
  geom_text(
  data = melted_row_summary %>% ungroup %>% select(-major_STs) %>% group_by(study,variable) %>% summarise(sumar= sum(proportion),count=sum(n)),
  inherit.aes = F,  
  aes(
    label = count,
    x = sumar+.026,
    y= variable
  ),
  size = 2.5,
) + scale_x_continuous(breaks = c(0,0.2,0.4,0.6,0.8,1),labels = c('0','20','40','60','80','100'),limits = c(0,1.01)) + ggtitle("All isolates") 
A
```

# Figure B. Non-carbapenemase isolates
```{r}
non_carbapenemase_isolates <- df %>% subset(carbapenemase=="No carbapenemase") %>% .$isolate_no
non_carbapenemase_isolates_1415 <- sum(grepl("PCMP",non_carbapenemase_isolates))
non_carbapenemase_isolates_2123 <- sum(grepl("INT",non_carbapenemase_isolates))

melted_row_no_carb<- df_carb_omp %>% select(-isolate_no) %>% subset(rownames(.) %in% non_carbapenemase_isolates) %>% reshape2::melt(c("study","major_STs")) %>% subset(value == 1)  
# Calculate proportion of isolates in study but retain the major_ST coloring
 
melted_row_no_carb_summary <- melted_row_no_carb %>% group_by(study,major_STs,variable) %>% summarise(n=sum(value))
melted_row_no_carb_summary$proportion <- ifelse(melted_row_no_carb_summary$study =='2021-23',melted_row_no_carb_summary$n/non_carbapenemase_isolates_2123,melted_row_no_carb_summary$n/non_carbapenemase_isolates_1415)

# How to normalize data by count in study 
melted_row_no_carb_summary$variable <- recode(melted_row_no_carb_summary$variable,"ompK35_rare_truncation"='Rare ompK35 truncation',"ompK36_rare_truncation"='Rare ompK36 truncation',"OmpK36GD" = "GD loop 3 insertion in ompK36","OmpK36TD" = "TD loop 3 insertion in ompK36","OmpK36_c25t" = "C25T mutation in OmpK36") %>% gsub("Rare_","Rare ",.)
melted_row_no_carb_summary$variable <- factor(melted_row_no_carb_summary$variable,levels = melted_row_no_carb_summary %>% group_by(variable) %>% summarise(tot=sum(n)) %>% arrange(-tot) %>% .$variable)

B <- ggplot(data=melted_row_no_carb_summary,aes(y=variable,fill=major_STs,x=proportion)) + geom_bar(stat='identity') + facet_wrap(~study)  + theme_bw_me + theme(axis.text.x = element_text(angle=0, hjust = 1, vjust = 0.5)) +ST_major_scale + xlab("Percentage") + ylab(NULL) + xlim(NA,1.01) +  
  geom_text(
  data = melted_row_no_carb_summary %>% ungroup %>% select(-major_STs) %>% group_by(study,variable) %>% summarise(sumar= sum(proportion),count=sum(n)),
  inherit.aes = F,  
  aes(
    label = count,
    x = sumar+.0225,
    y= variable
  ),
  size = 2.5,
) + scale_x_continuous(breaks = c(0,0.2,0.4,0.6,0.8,1),labels = c('0','20','40','60','80','100'),limits = c(0,1.01)) + ggtitle("Non-carbapenemase-containing isolates") 
B
```

```{r,fig.width=8,fig.height=12}
legends <- cowplot::get_legend(A)
AB <- cowplot::plot_grid(A + theme(legend.position = 'none'),B+ theme(legend.position = 'none'),ncol=1,labels = c("A","B"),rel_heights = c(1,0.75))
figure <- cowplot::plot_grid(AB,legends,rel_heights = c(1,0.075),ncol=1)

figure
```

```{r}
ggsave(filename = "./figures/s_figure_2_carbapenem_resistance_associated_genotypes_count.png",plot=figure,width = 8,height = 12,dpi=900,bg = 'white')
```
