---
title: "Supplemental Figure 12: Resistance histograms"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---
 
```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms')
```

# Environment

```{r}
# Packages
packages <- c("tidyverse","ComplexHeatmap",'ggalluvial','ape','ggtree')
lapply(packages,library,character.only=T)

# Functions
source("./lib/consistent_themes.R")

# Print environment
Sys.info()
sessionInfo()
```

# Load data

```{r}
df <- readRDS("./data/dataset/CA_LTACH_first_clinical_per_quarter_CRKP_genomes_merged_studies_metadata.RDS")   
df_201415 <- df%>% subset(study == "2014-15")
df_202123<- df%>% subset(study == "2021-23")
```

# Figure 
## Code
```{r}
range_dataset <- cbind.data.frame(name = c("Meropenem-vaborbactam",
                                           "Omadacycline",
                                           "Colistin",
                                           "Plazomicin",
                                           "Imipenem",
                                           "Fosfomycin",
                                           "Ceftolozane-tazobactam",
                                           "Delafloxacin",
                                           "Ceftazidime-avibactam",
                                           "Meropenem",
                                           "Eravacycline",
                                           "Cefiderocol",
                                           "Imipenem-relebactam",
                                           "Cefiderocol"),
                                  min = c(0.008,
                                          0.12,
                                          0.25,
                                          0.12,
                                          2,
                                          64,
                                          0.06,
                                          0.12,
                                          0.12,
                                          0.25,
                                          0.03,
                                          0.03,
                                          0.03,
                                          NA) ,
                                  max = c(16,
                                          8,
                                          4,
                                          4,
                                          16,
                                          128,
                                          8,
                                          1,
                                          32,
                                          8,
                                          8,
                                          32,
                                          16,
                                          NA))
                                    
```


```{r,message=F,error=F,warning=F,fig.width=15,fig.height=7.5} 
create_MIC_histogram <- function(phenotype_cont, phenotype_log, phenotype_cat = NULL, phenotype_name) {
  # Combine log and cat data safely
  data <- tibble(phenotype_log = phenotype_log, phenotype_cat = phenotype_cat,phenotype_cont = phenotype_cont) %>% subset(phenotype_cat != "ERROR")
  
  # Create renaming vector to map log values to continuous (for better axis labels)
  renaming_vector <- unique(phenotype_cont) %>% subset(is.na(.)==F)
  names(renaming_vector) <- unique(phenotype_log) %>% subset(is.na(.)==F) %>% as.numeric 
  
  # Rename variable
  phenotype_name <-  recode_resistance_variables(paste0(phenotype_name,"_dich_num"))
  
  min_val <- subset(range_dataset,name == phenotype_name) %>% .$min
  max_val <- subset(range_dataset,name == phenotype_name) %>% .$max
  
  renaming_vector <- ifelse(renaming_vector>=max_val,paste0("≥",renaming_vector),
         ifelse(renaming_vector<=min_val,paste0("≤",renaming_vector),renaming_vector))
  
  x_axis_name <- ifelse(phenotype_name =="Cefiderocol", "Cefiderocol zone of inhibition (mm)",paste0(phenotype_name, " (µg/mL)"))
  
  # Plot
  if(phenotype_name == "Cefiderocol"){
    
  histogram <- ggplot(data, aes(x = phenotype_cont,fill=phenotype_cat)) +
    geom_histogram(bins = 33)  +
    ylab("Isolates") +
    xlab(x_axis_name)  + theme_bw_me + resistance_cat_scale + theme(axis.text = element_text(size=7.5),axis.title = element_text(size=10))
    
  } else {
  histogram <- ggplot(data, aes(x = phenotype_log,fill=phenotype_cat)) +
    geom_bar()  +
    ylab("Isolates") +
    xlab(x_axis_name) + scale_x_continuous(breaks=as.numeric(names(renaming_vector)), labels=renaming_vector)  + theme_bw_me + resistance_cat_scale + theme(axis.text = element_text(size=7.5),axis.title = element_text(size=10))
  }
  return(histogram)
}

# Figure
MIC_variables_no_blbli <- df_202123 %>% select(paste0(MIC_variables,"_dich_num")) %>% colSums(na.rm = T) %>% sort(decreasing = T) %>% names(.) %>% gsub("_dich_num","",.) %>% subset(. != 'blbli')
 
figures <- lapply(MIC_variables_no_blbli,FUN=function(x){
  create_MIC_histogram(phenotype_cont= df_202123[[paste0(x,"_num")]],phenotype_log = df_202123[[paste0(x,"_log_2")]],phenotype_cat = df_202123[[paste0(x,"_cat")]],phenotype_name = x) + theme(legend.position = 'none')
}) %>% `names<-`(MIC_variables_no_blbli)

fig_w_legend <-  create_MIC_histogram(df_202123[["MERO_num"]],df_202123[["MERO_log_2"]],df_202123[["MERO_cat"]],phenotype_name = "x")
fig_legend <- cowplot::get_legend(fig_w_legend)
figures[["legend"]] <- fig_legend
``` 

## Figure
```{r,message=F,error=F,warning=F,fig.width=10.5,fig.height=10.5} 
histogram_figs <- cowplot::plot_grid(plotlist=figures,ncol=3,labels=c(LETTERS[1:length(figures) - 1],""),label_size = 12)
histogram_figs
```

# Save figure
```{r}
ggsave(plot = histogram_figs, filename = "./figures/s_figure_12_resistance_histograms.png", width = 10.5, height = 10.5, bg = "white",dpi=900)
```