---
title: "Supplemental Figure 11: Plasmids on phylogeny"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir = '~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms')
```

# Environment

```{r}
# Packages
packages <- c("tidyverse","ComplexHeatmap",'ape','ggtree','ggnewscale')
lapply(packages,library,character.only=T)

# Functions
source("./lib/consistent_themes.R") 

# Print environment
Sys.info()
sessionInfo()
```

# Load data

```{r}
df <- readRDS("./data/dataset/CA_LTACH_first_clinical_per_quarter_CRKP_genomes_merged_studies_metadata.RDS")   
```

# Coordinate ST data

```{r}  
df$Species_ST_recode_no_species <- gsub("Klebsiella pneumoniae ","",df$Species_ST)
 
df_201415 <- df%>% subset(study == "2014-15")
df_202123<- df%>% subset(study == "2021-23")
```

# Load carbapenemase data
```{r}
carbapenemase_content <- readRDS("./data/carbapenemase_content/carbapenemase_content_merged_studies.RDS")
df <- left_join(df,carbapenemase_content)
df$carbapenemase_md <- format_carbapenemase(df$carbapenemase) 
```

# Load plasmid data
```{r} 
KPC_plasmid_matrix <- readRDS("./data/carbapenemase_content/carbapenemase_plasmid_matrix.RDS") %>% subset(rownames(.) %in% df$isolate_no)
```

# Phylogeny 
## Load tree
```{r}
tr <- read.tree("./data/phylogeny/INTEGRATE/INTEGRATE_CRKP.treefile") 
```

## Scale creation
```{r} 
geno_vars <- colnames(KPC_plasmid_matrix %>% select_if(colSums(.)>0)) %>% subset(!.%in% c("study","major_STs","No carbapenemase"))
genotype <- KPC_plasmid_matrix %>% subset(rownames(.) %in% tr$tip.label) %>% select(geno_vars) %>% drop_na()  %>% select_if(colSums(.) >0) %>% ComplexHeatmap::Heatmap()
plasmid_matrix <- KPC_plasmid_matrix %>% select(genotype@column_names_param$labels[ComplexHeatmap::column_order(genotype)]) %>% mutate_all(as.factor) 
colnames(plasmid_matrix) <- recode_genotypes(colnames(plasmid_matrix))
```

## Phylogeny creation
```{r,fig.width=9.25,fig.height=9.25}  
df <- as.data.frame(df)
rownames(df) <- df$isolate_no
p0 <- gheatmap(ggtree(tr),df %>% select(Species_ST_recode) %>% `colnames<-`("Sequence type"),color = NULL,width=0.05,colnames_position = 'top',colnames_angle = 90,hjust=0, colnames_offset_y = 0.25) + ST_scale_4_row  + theme(legend.key = element_rect(colour = c('black'))) + new_scale_fill() 
p1 <- gheatmap(p0,df %>% select(carbapenemase_md) %>% `colnames<-`("Carbapenemase"),color = NULL,width=0.05,offset=0.0035,colnames_position = 'top',colnames_angle = 90,hjust=0, colnames_offset_y = 0.25)  + carbapenemase_scale_4_row + theme( legend.key = element_rect(colour = c('black'))) + new_scale_fill() 
figure <- gheatmap(p1,plasmid_matrix,color = NULL,width=0.05*length(geno_vars),offset=0.007,colnames_position = 'top',colnames_angle = 90,hjust=0, colnames_offset_y = 0.25)  + carbapenemase_presence_scale + ylim(NA,565) + theme(legend.position = 'bottom', legend.key = element_rect(colour = c('black')),legend.text=element_markdown())  + geom_treescale(y = -14, offset = 2)
```

# Edited figure
```{r,fig.width=10.5,fig.height=10.5}  
figure_legend <- cowplot::get_legend(figure + theme(legend.key.size = unit(0.5,"cm")))

final_figure <- cowplot::plot_grid(figure + theme(legend.position = 'none',
                                                  plot.margin = margin(b=-25)),figure_legend,ncol=1,rel_heights = c(1,0.15))
final_figure
```

# Save

```{r}
ggsave(filename = "./figures/s_figure_11_carbapenem_plasmids_phylogeny.png",plot=figure,width = 10.5, height = 10.5 ,dpi=900,bg = 'white')
```