---
title: "Penn_KPC_dataset_qcd_curation"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/')
```

```{r environment, echo=F, message=FALSE, include=F, results=F}
# Environment

#Packages
packages <- c("tidyverse") 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()

# Functoins
source("~/Desktop/gl_nfs/Project_Penn_KPC/Analysis/Combination_resistance/pre-intro-blbli-resistance-ms/scripts/dataset_curation/metadata_curation_functions.R")
```

# Load data
```{r} 
df_2014_15 <- readxl::read_excel("~/Desktop/gl_nfs/Project_Penn_KPC/Analysis/data/459_patients_data_for_posting.xls")  %>% as.data.frame
df_2014_15 <- df_2014_15 %>% subset(state == 'CA')  
df_2014_15$sample_id <- as.character(df_2014_15$isolate_no)
df_2014_15$isolate_no <-  paste0("PCMP_H",df_2014_15$isolate_no)   
df_2014_15$participant_id <- as.character(df_2014_15$Patient_ID)
```

# Resitance
## Old
### Load data
```{r}
SENSITITRE <- readxl::read_excel("~/Desktop/gl_nfs/Project_Penn_KPC/Analysis/Antibiotic_resistance/data/SENSITITRE MICs.xlsx", range = "B1:N460") %>% as.data.frame
SENSITITRE <- SENSITITRE %>% mutate(isolate_no = paste0("PCMP_H",str_remove(gsub('CRKP_','',SENSITITRE$ISOLATES),"^0+"))) %>% `rownames<-`(.$isolate_no)

# PCMP_H472 & PCMP_H473 were excluded due to data reporting issues
SENSITITRE <- subset(SENSITITRE,!isolate_no %in% c("PCMP_H472","PCMP_H473"))
```

### Clean variables
```{r}
## Convert names
SENSITITRE <-  dplyr::rename(SENSITITRE,MVB = "MEV",IR = "IMK", CST = "COL", AMK = "AMI", FOS = "FOS+",PT = "P/T4")

## Fix MVB data due to miscoding (vaborbactom is a constant 8 µg/mL not 4 µg/mL)
table(SENSITITRE$MVB)
SENSITITRE <- SENSITITRE %>% mutate(MVB = dplyr::recode(MVB,"2/4" = "2/8"))

## Create MIC Variable
MIC_variables <- c("Ceftazidime-avibactam"="CZA","Meropenem-vaborbactam"="MVB","Imipenem-relebactam"="IR","Tigeycline"="TGC","Colistin"="CST","Amikacin"="AMK","Plazomicin"="PLZ","MERO","IMI","FOS")

## Numerize MIC Data
for(i in MIC_variables){
  SENSITITRE[,paste0(i,"_num")] <- SENSITITRE[,paste0(i)]  %>% gsub("≤","",.) %>% gsub(">","",.) %>% gsub("/.","",.) %>% trimws(.,'both') %>% as.numeric
}

## Factorize Raw MIC Data
for(i in MIC_variables){
  SENSITITRE[,i] <- factorize_MIC(SENSITITRE,i)
}

## Log-2 Transform Data
for(i in MIC_variables){
  SENSITITRE[,paste0(i,"_log_2")] <- log2(SENSITITRE[,paste0(i,"_num")])
}
```

## Convert Raw MIC data to phenotypic resistance categories
Select references:
1. https://academic.oup.com/cid/article/72/8/1484/5868454?login=true
2. https://www.sciencedirect.com/science/article/pii/S0255085721041062
```{r}
SENSITITRE <- SENSITITRE %>% mutate(
  ### Meropenem (MERO): ≤1/2/≥4
  MERO_cat = ifelse(MERO_num <= 1,"S",ifelse(MERO_num >= 4,"R","I")),
  ### Imipenem (IMI): ≤1/2/≥4
  IMI_cat = ifelse(IMI_num <= 1,"S",ifelse(IMI_num >= 4,"R","I")),
  ### Ceftazidime-avibactam: Susceptible (MIC≤8/4), Resistant (MIC≥16/4)  
  CZA_cat = ifelse(CZA_num <= 8,"S",ifelse(CZA_num >= 16,"R","")),
  ### Meropenem-vaborbactam (MVB): Susceptible (MIC≤4/8), Intermediate (MIC=8/8), Resistant (MIC≥16/8)  
  MVB_cat = ifelse(MVB_num <= 4,"S",ifelse(MVB_num == 8,"I","R")),
  ### Imipenem-relebactam (I-R): Susceptible (MIC≤1/4), Intermediate (MIC=2/4), Resistant (MIC≥4/4)  
  IR_cat = ifelse(IR_num <= 1,"S",ifelse(IR_num == 2,"I","R")),
  ### Tigecycline (TGC): Susceptible (MIC≤2), Intermediate (MIC=4), Resistant (MIC≥8)  
  TGC_cat = ifelse(TGC_num <= 2,"S",ifelse(TGC_num == 4,"I","R")),
  ### Colistin (CST): Intermediate (MIC≤2), Resistant (MIC≥4)
  CST_cat = ifelse(CST_num <= 2,"I",ifelse(CST_num >= 4,"R","")),
  ### Amikacin (AMK): Susceptible (MIC≤16), Intermediate (MIC=32), Resistant (MIC≥64)   
  AMK_cat =  ifelse(AMK_num <= 16,"S",ifelse(AMK_num == 32,"I","R")),
  ### Plazomicin (PLZ): Susceptible (MIC≤2), Intermediate (MIC=4), Resistant (MIC≥8) 
  PLZ_cat = ifelse(PLZ_num <= 2,"S",ifelse(PLZ_num == 4,"I","R")),
  FOS_cat = ifelse(FOS == ">64","I","S")) 

## Factorize Categorical Data
MIC_variables_cat <- paste0(MIC_variables,"_cat") 
for(i in MIC_variables_cat){
  SENSITITRE[,i] <- factor(as.vector(SENSITITRE[,i]),
                           levels = c("S","I","R"),
                           labels = c("Susceptible","Intermediate","Resistant"))
}

## Create Binary Non-Susceptible Variable 
MIC_variables_no_CST<- c("MERO","IMI","MVB","IR","CZA","AMK","PLZ","TGC","FOS")
for(i in MIC_variables_no_CST){
  SENSITITRE[,paste0(i,"_dich")] <- binarize_MIC(SENSITITRE,paste0(i,"_cat"))
}
SENSITITRE$CST_dich <- ifelse(SENSITITRE$CST_cat == "Resistant","Non-Susceptible","Susceptible")

## Factorize Dichotomous Data
MIC_variables_dich <- paste0(MIC_variables,"_dich") 
for(i in MIC_variables_dich){
  SENSITITRE[,i] <- factor(as.vector(SENSITITRE[,i]),
                           levels = c("Susceptible","Non-Susceptible"),
                           labels = c("Susceptible","Non-Susceptible"))
}

## Numerical Dichotemous Variable for Resistance
for(i in MIC_variables_dich){
  SENSITITRE[,paste0(i,"_num")] <- ifelse(SENSITITRE[,i] == "Susceptible",0,1)
}
```

### Create BL/BLI combination therapy outcome
```{r}
SENSITITRE$blbli_dich <- ifelse(SENSITITRE$MVB_dich=="Non-Susceptible" | SENSITITRE$IR_dich=="Non-Susceptible"  | SENSITITRE$CZA_dich == "Non-Susceptible","Non-Susceptible","Susceptible")  %>% factor(.,levels = c("Susceptible","Non-Susceptible"),labels = c("Susceptible","Non-Susceptible"))
SENSITITRE$blbli_dich_num <- ifelse(SENSITITRE$blbli_dich == "Non-Susceptible",1,0) 
```

### Merge
```{r}
df_2014_15 <- left_join(SENSITITRE,df_2014_15) %>% subset(state=='CA')
```

### Merge with QCD data
## Load and curate
```{r}
escre_list <- read.csv("./Project_INTEGRATE/Analysis/data/INTEGRATE_MERLIN_WGS_Species_calls_030925_LLC.csv")
escre_species <- subset(escre_list,Enterobacterales == T) %>% .$Species
qcd_201415 <- read.csv("./Project_Penn_KPC/Sequence_data/illumina_fastq/master_qc_summary.csv")  %>% subset(grepl("NEG_CTL",Sample)==F) 
colnames(qcd_201415) <- snakecase::to_snake_case(colnames(qcd_201415))
qcd_201415$qc_pass <- qcd_201415$qc_check=="PASS" 

qcd_201415$CRE <- qcd_201415$species %in% escre_species 
qcd_201415$isolate_no <- qcd_201415$sample

df_2014_15 <- left_join(df_2014_15,qcd_201415) 

paste0("Number of isolates: ",nrow(df_2014_15))
paste0("Number of qc_passing isolates: ",sum(df_2014_15$qc_pass==TRUE))
paste0("Number of qc_passing CRE isolates: ",sum(df_2014_15$qc_pass==TRUE & df_2014_15$CRE==TRUE))
```

# Save
```{r}
saveRDS(df_2014_15,"./Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms/data/dataset/Penn_KPC_metadata_qcd_merged.RDS")
```
