---
title: "Curate betalactamase and OMP mutation matrix"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms')
```

# Environment
```{r}
# Packages
packages <- c("tidyverse")
lapply(packages,library,character.only=T)

# Functions
source("./lib/consistent_themes.R")

# Print environment
Sys.info()
sessionInfo() 
```

# Load data
```{r}
df <- readRDS("./data/dataset/CA_LTACH_CRE_genomes_merged_studies_metadata.RDS")   
df_first <- readRDS("./data/dataset/CA_LTACH_first_clinical_per_quarter_CRKP_genomes_merged_studies_metadata.RDS")   
```

# Load amrfinder
```{r}
amrfinder <- readRDS("./data/amrfinder/amrfinder_curated.RDS")
amrfinder <- subset(amrfinder,amrfinder$isolate_no %in% df$isolate_no) 
```

# Get list of blactamases
```{r}
amrfinder_beta <- amrfinder %>% subset(class == "BETA-LACTAM")
amrfinder_beta_bla <- amrfinder %>% subset(class == "BETA-LACTAM"& grepl("bla",element_symbol_renamed))
 
amrfinder_carb_bla <- amrfinder %>% subset(subclass == "CARBAPENEM" & grepl("bla",element_symbol_renamed) | grepl("KPC|NDM|VIM|IMP",element_symbol_renamed) | grepl("OXA-48 family",element_symbol_renamed))
amrfinder_carb_ompK <- amrfinder %>% subset(subclass == "CARBAPENEM" & ! element_symbol_renamed %in% amrfinder_carb_bla$element_symbol_renamed)
amrfinder_matrix <- readRDS("./data/amrfinder/amrfinder_matrix.RDS")  %>% subset(rownames(.) %in% df$isolate_no) 
amrfinder_matrix_beta <- amrfinder_matrix %>% select(any_of(sort(c(unique(amrfinder_beta$element_symbol_renamed)))))
amrfinder_matrix_carb <- amrfinder_matrix %>% select(any_of(sort(c(unique(amrfinder_carb_bla$element_symbol_renamed)))))
```

# Load kleborate
```{r,fig.width=9.5,height=6.7857}
kleborate_matrix <- readRDS("./data/kleborate/kleborate_kpsc_both_studies_matrix.RDS") %>% select_if(!colnames(.) %in% c("OmpK36GD","OmpK36TD")) 
kleborate_matrix$isolate_no <- rownames(kleborate_matrix) 
```

# Merge with amrfinder matrix
```{r,fig.width=9.5,height=6.7857}
df <- left_join(df,kleborate_matrix) %>% left_join(amrfinder_matrix_beta %>% mutate(isolate_no = rownames(.))) %>% as.data.frame
rownames(df) <- df$isolate_no 
df_carb_omp <- df %>% select(any_of(c(unique(amrfinder_beta$element_symbol) ,colnames(kleborate_matrix))))   

saveRDS(df_carb_omp,"./data/carbapenemase_content/carbapenem_resistance_genotype_content_merged_datasets.RDS")
```

# First isolate curation
```{r}
df_carb_omp_first <- subset(df_carb_omp,isolate_no %in% df_first$isolate_no)  %>% select(-isolate_no) %>% select_if(colSums(.)>0)
```

```{r}
# Omp mutations
kleb_matrix_count <- df_carb_omp_first %>% select(any_of(colnames(kleborate_matrix))) %>% colSums() %>% sort
mutations_over_4 <- names(subset(kleb_matrix_count,kleb_matrix_count>4))
muts_under <- subset(names(kleb_matrix_count),!names(kleb_matrix_count) %in% mutations_over_4)
ompK35_truncations_under_4 <- subset(muts_under,grepl("K35-",muts_under))
ompK36_truncations_under_4 <- subset(muts_under,grepl("K36-",muts_under))

df_carb_omp_first$ompK35_rare_truncation <- df_carb_omp_first %>% select(ompK35_truncations_under_4) %>% rowSums(.) %>% {ifelse(.>0,1,0)}
df_carb_omp_first$ompK36_rare_truncation <- df_carb_omp_first %>% select(ompK36_truncations_under_4) %>% rowSums(.) %>% {ifelse(.>0,1,0)}

df_carb_omp_first <- df_carb_omp_first %>% select(-muts_under)

# bla genotpyes
bla_count <- df_carb_omp_first %>% select(any_of(colnames(amrfinder_matrix_beta))) %>% colSums() %>% sort
bla_over_4 <- names(bla_count)[bla_count>4] 
bla_under_4 <- names(bla_count)[bla_count<4]

families_under_four <- str_split(bla_under_4,"-",simplify = T) %>% .[,1] %>% gsub("bla","",.)  %>% str_split(.,"_",simplify=T) %>% .[,1]%>% unique %>% sort

store_thes <- lapply(families_under_four,FUN=function(x,df_carb_omp_first,bla_under_4){
  cols_of_family <- bla_under_4[grepl(x,bla_under_4)]
  new_col_name <- ifelse(x == "ompK35",
                         "Rare_ompK35_insertion",
                         ifelse(x=="ompK36","Rare_ompK36_insertion",paste0("Rare_bla",x))) 
  df_carb_omp_first[[new_col_name]] <<- df_carb_omp_first %>% select(all_of(cols_of_family)) %>% rowSums() %>% {ifelse(.>0,1,0)}
},df_carb_omp_first,bla_under_4)  

df_carb_omp_first <- df_carb_omp_first %>% select(-bla_under_4)
```

```{r}
saveRDS(df_carb_omp_first,"./data/carbapenemase_content/carbapenem_resistance_genotype_content_merged_first_clinical_CRKP_isolate_per_quarter.RDS")
```
