---
title: "Supplemental Table 2: Sequencing QC data for study isolates"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms/')
```
 
# Environment

```{r environment, echo=F, message=FALSE, include=T, results=T}
#Packages
packages <- c("tidyverse",'kableExtra') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Functions
source("./lib/consistent_themes.R")

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()  
```

# Load SRA metadata
```{r}
isolate_data_merged <- readRDS("./data/NCBI_info/NCBI_merged_dataset.RDS")
```

# View content
```{r}
head(isolate_data_merged) %>% favorite_kable()
```

# Format content
```{r}
colnames(isolate_data_merged) <- recode(colnames(isolate_data_merged),
                                        "isolate_no" = "Isolate",
                                        "accession" = "Accession",
                                        'instrument' = "Instrument",
                                        "study" ="Study",
                                        "source_simplified" = "Source category",
                                        "hospital_location_recode" = "Facility",
                                        "total_length" = "Assembly length (bp)",
                                        "total_of_contigs" = "Number of contigs",
                                        "n_50" = "N50",
                                        "coverage" = "Coverage",
                                        "species" = "Species",
                                        "ST" = "Sequence type (ST)"
                                        )

isolate_data_merged$`Source category` <- recode(isolate_data_merged$`Source category`,
                                                "urine" = "Urine",
                                                'respiratory' = "Respiratory",
                                                "blood" = "Blood",
                                                "wound" = "Wound",
                                                "other" = "Other")
head(isolate_data_merged) %>% favorite_kable()
```

# Save table
```{r}
saveRDS(isolate_data_merged,"./tables/s_table_2_SRA_metadata.RDS")
write.csv(isolate_data_merged,"./tables/s_table_2_SRA_metadata.csv")
```
 