---
title: "Supplemental Table 1: Specimen sites in INTEGRATE"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/')
```


```{r} 
# Packages
packages <- c("tidyverse","gridExtra","kableExtra","tableone","gontjesr")
lapply(packages,library,character.only=T)

# Functions
source("./Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms/lib/consistent_themes.R")

# Print environment
Sys.info()
sessionInfo() 
```


```{r}
df <- readRDS("~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/2025-09-18_master_kpn_first_isolate_dataset_curation/results/CA_clinical_CRKP_first_isolate_metadata_091825.RDS")  %>% subset(is.na(source_site) ==F)

df_202123 <- subset(df,study == "2021-23")
```

```{r}
source_table <- convert_tableone_into_df(df_202123,vars = 'source_site')  

favorite_kable(source_table)

write_csv(source_table,"./Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms/tables/s_table_1_specimen_sampling.csv")
```

