---
title: 'Table 1: Baseline characteristics'
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms')
```


```{r} 
# Packages
packages <- c("tidyverse","gridExtra","kableExtra","tableone","gontjesr")
lapply(packages,library,character.only=T)

# Functions
source("./lib/consistent_themes.R")

# Print environment
Sys.info()
sessionInfo()
```

# Load data

```{r}
df <- readRDS("./data/dataset/CA_LTACH_first_clinical_per_quarter_CRKP_genomes_merged_studies_metadata.RDS")  
``` 

```{r}
df_w_metadata <- df %>% subset(has_full_metadata==T & first_isolate==T) 
df_w_metadata$non_hispanic_white <- df_w_metadata$participant_race=="Caucasian" & df_w_metadata$participant_ethnicity == "Not Hispanic"
```

```{r}
table <-  convert_tableone_into_df(dataset = df_w_metadata, vars = c("participant_age_at_first_enc","participant_sex","participant_race","non_hispanic_white",'source_simplified',"los_before_culture"), factorVars = c("participant_sex","participant_race","non_hispanic_white",'source_simplified'),strata='study',outcome_names = c("2014-15","2021-23"))

table$Variable <- recode(table$Variable,
                         "participant_age_at_first_enc (mean (SD))" = "Age in years, mean (SD)",
                         "participant_sex = male (%)" = "Male sex",
                         "participant_race (%)" = "Race",
                         "participant_ethnicity = Not Hispanic (%)"= "Non-Hispanic White",
                         "source_simplified (%)" = "Site of infection",
                         "   blood" = '   Blood',
                         '   other'='   Other',
                         '   urine'='   Urine',
                         '   respiratory'='   Respiratory',
                         '   wound'='   Wound',
                         "   more than one race"="   More than one race",
                         "non_hispanic_white = TRUE (%)" = "Non-Hispanic white",
                         "los_before_culture (mean (SD))" = "Length of stay before culture, mean (SD)")

table %>% favorite_kable 

saveRDS(table,"./tables/table_1_demographics.RDS")
write_csv(table,"./tables/table_1_demographics.csv")
```
