---
title: "Results section 3: Carbapenemase data"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms')
```

```{r}
# Packages
packages <- c("tidyverse","gridExtra","kableExtra","tableone","gontjesr","cowplot","ComplexHeatmap",'ggalluvial','ape','ggtree')
lapply(packages,library,character.only=T)

# Functions
source("./lib/consistent_themes.R")

# Print environment
Sys.info()
sessionInfo()
```

# Load data

```{r}
df <- readRDS("./data/dataset/CA_LTACH_first_clinical_per_quarter_CRKP_genomes_merged_studies_metadata.RDS")   
   
df_201415 <- df%>% subset(study == "2014-15")
df_202123 <- df%>% subset(study == "2021-23") 
```

# Coordinate ST data

```{r} 
break_of_sts <-  c(sort(unique(df$Species_ST_recode %>% subset(.!="Singleton STs"))),"Singleton STs")
break_of_sts_renamed <- gsub("Klebsiella pneumoniae ","",break_of_sts)
       
ST_scale <- scale_fill_manual(breaks = break_of_sts,values = c(hues::iwanthue(n = length(unique(df$Species_ST_recode)) -1),"lightgray"),labels = break_of_sts_renamed,name = "Sequence type", guide = guide_legend(ncol=7, title.position = "top", label.position = "right"))

ST_palette <- ST_scale$palette(1) 
ST_palette <- c(ST_palette,"Other STs"='lightgray')
ST_major_scale <- scale_fill_manual(values = ST_palette,name = "Major sequence types (STs)")
```

# Load  carbapenemase content
```{r}
carbapenemase_content <- readRDS("./data/carbapenemase_content/carbapenemase_content_merged_studies.RDS")
df <- left_join(df,carbapenemase_content)

df$blaKPC_presence <- grepl("KPC",df$carbapenemase_family) 
df$blaKPC_2 <- grepl("KPC-2",df$carbapenemase)  & !grepl("KPC-29",df$carbapenemase)
df$blaNDM <- grepl("NDM",df$carbapenemase)
df$blaOXA <- grepl("OXA",df$carbapenemase)
df$no_carbapenemase <- grepl("No carbapenemase",df$carbapenemase_family) 
```

# Load omp matrix
```{r}
carb_omp <-  readRDS("./data/carbapenemase_content/carbapenem_resistance_genotype_content_merged_datasets.RDS")%>% subset(isolate_no %in% df$isolate_no)
df <- left_join(df,carb_omp)

df$OmpK36_mutation <- df %>% as.data.frame %>% select_if(grepl("OmpK36",colnames(.)) | grepl("ompK36",colnames(.))) %>% rowSums() %>% {ifelse(.>0,1,0)}
df$OmpK35_mutation <- df %>% as.data.frame %>% select_if(grepl("OmpK35",colnames(.)) | grepl("ompK35",colnames(.))) %>% rowSums() %>% {ifelse(.>0,1,0)}
df$porin_mutation <-  df$OmpK36_mutation  == 1 | df$OmpK35_mutation ==1
```  

# Differences across study periods in carbapenemase
```{r}
convert_tableone_into_df(dataset = df,vars = c('blaKPC_presence',"blaNDM","blaOXA",'carbapenemase',"porin_mutation","OmpK35_mutation","OmpK36_mutation"),strata = 'study',outcome_names = c("2014-15","2021-23"),argsNormal = "carbapenemase",factorVars = c('carbapenemase',"blaNDM","blaOXA","porin_mutation","OmpK35_mutation","OmpK36_mutation")) %>% favorite_kable()
```

# Differences among noncarbepenmase genomes
```{r}
df_nocarb <- df %>% subset(carbapenemase == 'No carbapenemase')
convert_tableone_into_df(dataset = df_nocarb,vars = c('blaKPC_presence',"blaNDM","blaOXA",'carbapenemase',"porin_mutation","OmpK35_mutation","OmpK36_mutation"),strata = 'study',outcome_names = c("2014-15","2021-23"),argsNormal = "carbapenemase",factorVars = c('carbapenemase',"blaNDM","blaOXA","porin_mutation","OmpK35_mutation","OmpK36_mutation")) %>% favorite_kable()
```

# Data across ST258
```{r}
df_ST258 <- subset(df,df$ST == "ST258")
df_ST258$GD_KPC2 <- df_ST258$ompK36_D135DGD==1 & df_ST258$`blaKPC-2` ==1
convert_tableone_into_df(dataset = df_ST258,vars = c('blaKPC_presence',"blaNDM","blaOXA",'carbapenemase',"porin_mutation","OmpK35_mutation","OmpK36_mutation","ompK36_D135DD","ompK36_D135DGD","ompK36_Q313STOP","ompK36_T136TDT","ompK36_W125STOP","GD_KPC2"),strata = 'study',outcome_names = c("2014-15","2021-23"),argsNormal = "carbapenemase",factorVars = c('carbapenemase',"blaNDM","blaOXA","porin_mutation","OmpK35_mutation","OmpK36_mutation","ompK36_D135DD","ompK36_D135DGD","ompK36_Q313STOP","ompK36_T136TDT","ompK36_W125STOP","GD_KPC2")) %>% favorite_kable()
```
