---
title: "Results section 2: Contextualize using 2014-15 study"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/')
```


```{r} 
# Packages
packages <- c("tidyverse","gridExtra","kableExtra","tableone","gontjesr")
lapply(packages,library,character.only=T)

# Functions
source("./Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms/lib/consistent_themes.R")

# Print environment
Sys.info()
sessionInfo()
```

# Load data
```{r}
df <- readRDS("~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/2025-09-18_master_kpn_first_isolate_dataset_curation/results/CA_clinical_CRKP_first_isolate_metadata_091825.RDS")  

df_201415 <- df%>% subset(study == "2014-15")
df_202123 <- df%>% subset(study == "2021-23")

df_202123_all <- readRDS("~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/2025-09-18_master_kpn_first_isolate_dataset_curation/results/CA_clinical_CRE_metadata_091825.RDS")  %>% subset(study == '2021-23')

df_202123_no_metadata <- df %>% subset(is.na(hospital_location) & study =='2021-23')
df_202123_w_metadata <- df %>% subset(is.na(hospital_location)==F& study =='2021-23')
df_w_metadata <- df %>% subset(is.na(hospital_location)==F)
```

# Contextualization using old study
```{r}
paste0("Number of specimens: ",nrow(df_201415))
paste0("Number of patients: ",length(unique(df_201415$participant_id)))

paste0("Minimum date: ",min(df_201415$date,na.rm=T))
paste0("Maximum date: ",max(df_201415$date,na.rm=T))

paste0("Number of facilities: ",length(unique(df_201415$hospital_location %>% subset(.!='NA'),na.rm=T)))
``` 

# Source data 
```{r}
df$blood <- ifelse(df$source_simplified == "blood",1,0)
df$other<- ifelse(df$source_simplified == "other",1,0)
df$resp<- ifelse(df$source_simplified == "respiratory",1,0)
df$urine<- ifelse(df$source_simplified == "urine",1,0)
df$wound <- ifelse(df$source_simplified == "wound",1,0)

paste0("Overall")
source_table <- table(df_w_metadata$study,df_w_metadata$source_simplified) 
source_table  
source_table %>% fisher.test(simulate.p.value = T)

convert_tableone_into_df(dataset=df %>% subset(is.na(hospital_location) == F),vars = c("source_simplified","blood","other","resp","urine","wound"),strata='study',outcome_names = c("2021-23",'2014-15'),factorVars = c("source_simplified","blood","other","resp","urine","wound")) %>% favorite_kable()

paste0("No paramount")
no_paramount <- df %>% subset(is.na(hospital_location) == F & hospital_location != "Paramount")
source_table_no_par <- table(no_paramount$study,no_paramount$source_simplified) 
source_table_no_par  
source_table_no_par %>% fisher.test(simulate.p.value = T)

convert_tableone_into_df(dataset=df %>% subset(is.na(hospital_location) == F & hospital_location != "Paramount"),vars = c("source_simplified","blood","other","resp","urine","wound"),strata='study',outcome_names = c("2021-23",'2014-15'),factorVars = c("source_simplified","blood","other","resp","urine","wound")) %>% favorite_kable()
```


# Frequency differences
## Count
```{r}
paste0("Differences by study")
hospital_study_table <- table(df_w_metadata$study,df_w_metadata$hospital_location) 
hospital_study_table
hospital_study_table %>% fisher.test(simulate.p.value = T)

paste0("Differences by study w/o Paramount")
df_no_par <- subset(df_w_metadata,hospital_location != "Paramount")
hospital_study_table_no_par <- table(df_no_par$study,df_no_par$hospital_location) 
hospital_study_table_no_par
hospital_study_table_no_par %>% fisher.test(simulate.p.value = T)
```
 