---
title: "Results section 1: Propsective surveillance of CRKP from California LTACHs"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = F,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms')
```


```{r} 
# Packages
packages <- c("tidyverse","gridExtra","kableExtra","tableone","gontjesr")
lapply(packages,library,character.only=T)

# Functions
source("./lib/consistent_themes.R")

# Print environment
Sys.info()
sessionInfo()
```

# Load data

```{r}
df <- readRDS("./data/dataset/CA_LTACH_first_clinical_per_quarter_CRKP_genomes_merged_studies_metadata.RDS")

df_201415 <- df%>% subset(study == "2014-15")
df_202123 <- df%>% subset(study == "2021-23") 
```

# Overview of clinical specimens from 2021-23
```{r}
paste0("Number of specimens: ",nrow(df_202123))
paste0("Number of patients: ",length(unique(df_202123$participant_id)))

paste0("Minimum date: ",min(df_202123$date,na.rm=T))
paste0("Maximum date: ",max(df_202123$date,na.rm=T))

paste0("Number of facilities: ",length(unique(df_202123$hospital_location)))
```

# INTEGRATE metadata availability
```{r}
df_202123_no_metadata <- df %>% subset(is.na(hospital_location) & study =='2021-23')
df_202123_w_metadata <- df %>% subset(is.na(hospital_location)==F & study =='2021-23')
df_w_metadata <- df %>% subset(is.na(hospital_location)==F)

paste0("Number of isolates with metadata: ",nrow(df_202123_w_metadata))
paste0("Proportion of isolates with metadata: ",round(nrow(df_202123_w_metadata)/ sum(nrow(df_202123_no_metadata),nrow(df_202123_w_metadata)),3))
```

# Anatomical site
```{r} 
convert_tableone_into_df(dataset=df_202123_w_metadata,vars = "source_simplified") 
``` 

# Contextualization using old study
```{r}
paste0("Number of specimens: ",nrow(df_201415))
paste0("Number of patients: ",length(unique(df_201415$participant_id)))

paste0("Minimum date: ",min(df_201415$date,na.rm=T))
paste0("Maximum date: ",max(df_201415$date,na.rm=T))

paste0("Number of facilities: ",length(unique(df_201415$hospital_location %>% subset(.!='NA'),na.rm=T)))
``` 

# Source data 
```{r}
df$blood <- ifelse(df$source_simplified == "blood",1,0)
df$other<- ifelse(df$source_simplified == "other",1,0)
df$resp<- ifelse(df$source_simplified == "respiratory",1,0)
df$urine<- ifelse(df$source_simplified == "urine",1,0)
df$wound <- ifelse(df$source_simplified == "wound",1,0)

paste0("Overall")
source_table <- table(df$study,df$source_simplified) 
source_table  
source_table %>% fisher.test(simulate.p.value = T)

convert_tableone_into_df(dataset=df ,vars = c("source_simplified","blood","other","resp","urine","wound"),strata='study',outcome_names = c('2014-15',"2021-23"),factorVars = c("source_simplified","blood","other","resp","urine","wound")) %>% favorite_kable()

paste0("Isolates with other source declaration: ")
df %>% subset(source_simplified == "other") %>% .$source
```

# Frequency differences
## Count
```{r}
paste0("Differences by study")
hospital_study_table <- table(df_w_metadata$study,df_w_metadata$hospital_location) 
hospital_study_table
hospital_study_table %>% prop.table() *100
hospital_study_table %>% fisher.test(simulate.p.value = T)

paste0("Differences by study w/o Paramount")
df_no_par <- subset(df_w_metadata,hospital_location != "Paramount")
hospital_study_table_no_par <- table(df_no_par$study,df_no_par$hospital_location) 
hospital_study_table_no_par
hospital_study_table_no_par %>% prop.table() *100
hospital_study_table_no_par %>% fisher.test(simulate.p.value = T)
```
 
# Age & sex differences
1. Preferentially select first isolate with metadata
```{r}
paste0("Total isolates: ",nrow(df))
df_w_metadata <- df %>% subset(has_full_metadata==T | participant_id == "13") %>% group_by(participant_id) %>% arrange(date) %>% slice(1)

df_w_metadata$non_hispanic_white <- df_w_metadata$participant_race=="Caucasian" & df_w_metadata$participant_ethnicity == "Not Hispanic"
paste0("Total patients with metadata: ",nrow(df_w_metadata))
paste0("Prop patients with metadata: ",nrow(df_w_metadata) / nrow(df) * 100)

convert_tableone_into_df(dataset = df_w_metadata, vars = c("participant_age_at_first_enc","participant_sex","participant_race","participant_ethnicity","non_hispanic_white"), factorVars = c("participant_sex","participant_race","participant_ethnicity","non_hispanic_white"),strata='study',outcome_names = c("2014-15","2021-23")) %>% favorite_kable
         
paste0("Wilcox test for age")                  
median_IQR <- function(variable,df){
  df_los_201415 <- subset(df,study =="2014-15") %>% .[[variable]]
  df_los_202123 <-  subset(df,study =="2021-23" ) %>% .[[variable]]
  median_overall <- median(df[[variable]],na.rm = T)
  median_201415 <- median(df_los_201415,na.rm=T)
  median_202123 <- median(df_los_202123,na.rm=T)
  IQR_overall <- IQR(df[[variable]],na.rm=T)
  IQR_201415 <- IQR(df_los_201415,na.rm=T)
  IQR_202123 <- IQR(df_los_202123,na.rm=T)
  form <- as.formula(paste0(variable, "~study"))
  pval <- wilcox.test(form,data=df) %>% .$p.value
  cbind.data.frame(Variable = variable,overall = paste0(median_overall," (",IQR_overall,")"), study_201415 = paste0(median_201415," (",IQR_201415,")"), study_202123 = paste0(median_202123," (",IQR_202123,")"), pvalue = pval)
}

median_IQR("participant_age_at_first_enc",df_w_metadata)
```

# Length of stay data
1. Preferentially select first isolate with metadata
```{r}
paste0("Number of participants with LOS data: ",nrow(df_w_metadata))
table(df_w_metadata$study)
 
paste0("Wilcox test for length of stay")
median_IQR("los_before_culture",df_w_metadata)
```
