---
title: "Results section 4: Carbapenemase plasmid"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms')
```

# Environment

```{r}
# Packages
packages <- c("tidyverse","gridExtra","kableExtra","tableone","gontjesr","cowplot","ComplexHeatmap",'ggalluvial')
lapply(packages,library,character.only=T)

# Functions
source("./lib/consistent_themes.R")

# Print environment
Sys.info()
sessionInfo()
```

# Load data

```{r}
df <- readRDS("./data/dataset/CA_LTACH_first_clinical_per_quarter_CRKP_genomes_merged_studies_metadata.RDS")   
```

# Coordinate ST data

```{r} 
break_of_sts <-  c(sort(unique(df$Species_ST_recode %>% subset(.!="Singleton STs"))),"Singleton STs")
break_of_sts_renamed <- gsub("Klebsiella pneumoniae ","",break_of_sts)
       
ST_scale <- scale_fill_manual(breaks = break_of_sts,values = c(hues::iwanthue(n = length(unique(df$Species_ST_recode)) -1),"lightgray"),labels = break_of_sts_renamed,name = "Sequence type", guide = guide_legend(nrow=3, title.position = "top", label.position = "right"))

df$Species_ST_recode_no_species <- gsub("Klebsiella pneumoniae ","",df$Species_ST)
 
df_201415 <- df%>% subset(study == "2014-15")
df_202123<- df%>% subset(study == "2021-23")
```

# Load carbapenemase data
```{r}
carbapenemase_content <- readRDS("./data/carbapenemase_content/carbapenemase_content_merged_studies.RDS")
df <- left_join(df,carbapenemase_content)
```

# Load plasmid data
```{r} 
KPC_plasmid_matrix <- readRDS("./data/carbapenemase_content/carbapenemase_plasmid_matrix.RDS") %>% subset(rownames(.) %in% df$isolate_no)
df <- left_join(df,KPC_plasmid_matrix %>% mutate(isolate_no = rownames(.)))
mobtyper_mat <- readRDS("./data/mobsuite/mobtyper_merged_w_carbapenemase_data.RDS") %>% subset(isolate_no %in% df$isolate_no)
```

# Descriptive statistics 

## KPC
```{r} 
paste0("Detected plasmids: ",paste0(KPC_plasmid_matrix %>% select(-Chromosome, -`No carbapenemase`) %>% select_if(colSums(.)>0)  %>% colnames(),collapse = " "))
paste0("Total plasmids: ",ncol(KPC_plasmid_matrix %>% select(-Chromosome, -`No carbapenemase`) %>% select_if(colSums(.)>0) ))
old_plasmids <- KPC_plasmid_matrix %>% subset(grepl("PCMP",rownames(.)))%>% select(-Chromosome, -`No carbapenemase`)   %>% colSums(.) %>% subset(.>0) %>% names
new_plasmids <- KPC_plasmid_matrix %>% subset(grepl("INT",rownames(.)))%>% select(-Chromosome, -`No carbapenemase`)  %>% colSums(.) %>% subset(.>0) %>% names
ggVennDiagram::ggVennDiagram(list(Old = old_plasmids, New = new_plasmids)) 

shared_kpc_plasmids <- intersect(old_plasmids,new_plasmids)
variables <-  c("carbapenemase_plasmid",shared_kpc_plasmids,'Chromosome')
gontjesr::convert_tableone_into_df(dataset=df %>% subset(carbapenemase_plasmid != "No carbapenemase"),vars =variables,strata='study',outcome_names = c("2014-15",'2021-23'),factorVars =variables,exact = 'carbapenemase_plasmid') %>% favorite_kable()

table(df %>% subset(carbapenemase_plasmid != "No carbapenemase") %>% .$carbapenemase_plasmid, df %>% subset(carbapenemase_plasmid != "No carbapenemase") %>% .$study) %>% fisher.test(simulate.p.value = T)
```

## ST258
```{r}
paste0("Total KPC plasmids: ",length(unique(df %>% subset(ST=='ST258') %>% .$carbapenemase_plasmid %>% subset(!. %in% c("Chromosome","No carbapenemase")))))

ST258_plasmids_old <- KPC_plasmid_matrix %>% subset(rownames(.) %in% c(df %>% subset(study == '2014-15' & ST=='ST258') %>% .$isolate_no)) %>% select(-Chromosome, -`No carbapenemase`)   %>% colSums(.) %>% subset(.>0) %>% names
                                                    
ST258_plasmids_new <- KPC_plasmid_matrix %>% subset(rownames(.) %in% c(df %>% subset(study == '2021-23' & ST=='ST258')%>% .$isolate_no)) %>% select(-Chromosome, -`No carbapenemase`)   %>% colSums(.) %>% subset(.>0) %>% names 

ggVennDiagram::ggVennDiagram(list(Old = ST258_plasmids_old, New = ST258_plasmids_new))

gontjesr::convert_tableone_into_df(dataset=df %>% subset(ST=='ST258' & carbapenemase_plasmid != "No carbapenemase"),vars = variables,strata='study',outcome_names = c("2014-15",'2021-23'),exact = 'carbapenemase_plasmid',factorVars = variables) %>% favorite_kable()

table(df %>% subset(carbapenemase_plasmid != "No carbapenemase" & ST=="ST258") %>% .$carbapenemase_plasmid, df %>% subset(carbapenemase_plasmid != "No carbapenemase" & ST=="ST258") %>% .$study) %>% fisher.test(simulate.p.value = T)
```
