---
title: "Results section 5: Differences in resistance across study periods"
author: "Kyle Gontjes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(knitr)
opts_knit$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA) 
opts_chunk$set(echo = T,warning = FALSE, message = FALSE,error=F,comment=NA)
opts_knit$set(root.dir='~/Desktop/gl_nfs/Project_INTEGRATE/Analysis/Resistance_dynamics/INTEGRATE-resistance-ms')
```

# Environment
```{r}
packages <- c("tidyverse",'kableExtra','tableone','gontjesr') 

#Load Packages
invisible(lapply(packages,library,character.only=T,quietly=T))

# Print environment
set.seed(45) 
Sys.info()
sessionInfo()
```

# Load data
```{r}
df <- readRDS("./data/dataset/CA_LTACH_first_clinical_per_quarter_CRKP_genomes_merged_studies_metadata.RDS")  

df$ST258 <- ifelse(df$Species_ST == "Klebsiella pneumoniae ST258",T,F)
df$ST17 <- ifelse(df$Species_ST == "Klebsiella pneumoniae ST17",T,F)

df_201415 <- df%>% subset(study == "2014-15")
df_202123 <- df%>% subset(study == "2021-23") 

shared_antibiotics <-  c('MERO',"IMI",'blbli','MVB','IR','CZA',"CST","PLZ","FOS")  %>% paste0(.,"_dich_num")
  
novel_antibiotics <-  c("FDC","CT","OMC","ERV","DLX")  %>% paste0(.,"_dich_num") 
```

# Isolates not all resistance outcomes
```{r}
isolates_2123 <- df_202123$isolate_no

na_data <- lapply(isolates_2123,FUN=function(x){
  df_202123 %>% subset(isolate_no == x) %>% select(shared_antibiotics,novel_antibiotics) %>% is.na() %>% rowSums() %>% `names<-`(x)
}) %>% unlist

at_least_one_missing <- df_202123 %>% subset(isolate_no %in% c(na_data %>% subset(.>0) %>% names())) %>% select(isolate_no,shared_antibiotics,novel_antibiotics)
 
at_least_one_missing %>% favorite_kable() 
```

# Differences across groups
```{r}
get_frequency_stats <- function(variable,df,name){
   freq <- df[[variable]] %>% sum(.,na.rm=T)
  tested <- df[[variable]] %>% subset(is.na(.)==F) %>% length
  not_tested <- nrow(df) - tested
  prop <- round(freq / tested * 100,2) 
  data.frame(variable = variable,study = name,freq,tested,prop,not_tested)
}

get_frequency_stats_compare <- function(variable,df,comparitor){
 data_table <- table(df[[variable]],df[[comparitor]],useNA = 'no') 
 test <- if(sum(unlist(data_table) <5)>0){
    fisher.test(data_table,simulate.p.value = T)
  } else {
    chisq.test(data_table)
  }
  group1 <- colnames(data_table)[1]
  group2 <- colnames(data_table)[2]
  
  group1_total <- sum(data_table[,1])
  group2_total <- sum(data_table[,2])
    
  group1_count <- data_table[,1] %>% subset(names(.)==1)
  group2_count <- data_table[,2] %>% subset(names(.)==1)
  
  group1_perc <- round(c(group1_count/group1_total)*100,1)
  group2_perc <- round(c(group2_count/group2_total)*100,1)
  
  sig_test <- ifelse(class(test)=="htest" & test$method == "Fisher's Exact Test for Count Data","Fisher's Exact Test","Chi-squared")
  p_value <- test$p.value
  
  data.frame(variable=variable,group1=group1,group1_total=group1_total,group1_count=group1_count,group1_perc=group1_perc,
             group2=group2,group2_total=group2_total,group2_count=group2_count,group2_perc=group2_perc,
             test=sig_test,p_value=p_value)
}

# New agents tested:
lapply(novel_antibiotics,FUN=get_frequency_stats,df=df_202123,name = '2021-23') %>% do.call(rbind,.) %>% favorite_kable()

#Comparisons
lapply(shared_antibiotics,FUN=get_frequency_stats_compare,df=df,comparitor='study') %>% do.call(rbind,.)%>% favorite_kable() 
```
